const SUPABASE_URL="https://lgpvvwymvqzhoqkpuyjv.supabase.co",SUPABASE_KEY="sb_publishable_OFguESiAuWQ8iHFzYgT-Mg_g-iL9-87",AUDIT_LOG_START="2026-08-08T12:42:30.541Z";
const labels={single:"Gemini AI"},betLabels={win:"単勝",place:"複勝",wide:"ワイド",quinella:"馬連"};
const stateLabels={stage1_pending:"一次判定待ち",stage1_rejected:"一次除外",evidence_pending:"外部情報取得待ち",evidence_ready:"情報準備完了",evidence_insufficient:"情報不足",selected:"Gemini選定",not_selected:"非選定",final_refresh_pending:"直前更新待ち",final_decided:"最終判断済み",invalid_output:"AI出力エラー",completed:"完了",failed:"エラー"};
let session=JSON.parse(localStorage.getItem("race-lab-session")||"null"),accounts=[],predictions=[],batches=[],allBets=[],selections=[],aiCalls=[],pipelineItems=[],rollovers=[],reservations=[],sourceSnapshots=[],pushSubscriptions=[],activeStrategy="single",selectedCall=null,lastDataAt=null,lastRefreshError=null;
const $=s=>document.querySelector(s),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),yen=n=>`${Number(n||0)<0?"-":""}¥${Math.abs(Number(n||0)).toLocaleString()}`,pct=n=>`${Number(n||0).toFixed(1)}%`,dt=v=>new Date(v).toLocaleString("ja-JP"),jst=v=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo"}).format(new Date(v));
const settlementOf=bet=>Array.isArray(bet?.settlements)?bet.settlements[0]:bet?.settlements;
async function auth(path,body){const r=await fetch(`${SUPABASE_URL}/auth/v1/${path}`,{method:"POST",headers:{apikey:SUPABASE_KEY,"content-type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.msg||d.error_description||d.message||"認証に失敗しました");return d}
async function api(table,q=""){const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}?${q}`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${session.access_token}`}}),d=await r.json();if(r.status===401){logout();throw new Error("ログイン期限が切れました")}if(!r.ok)throw new Error(d.message||"データ取得に失敗しました");return d}
async function optionalApi(table,q=""){try{return await api(table,q)}catch(error){console.warn(`${table}: ${error.message}`);return []}}
async function apiWrite(table,method,q="",body){const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}?${q}`,{method,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${session.access_token}`,"content-type":"application/json",Prefer:"resolution=merge-duplicates,return=minimal"},body:body==null?undefined:JSON.stringify(body)});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.message||"保存に失敗しました")}}
async function load(){try{$("#error").hidden=true;$("#refresh-data").disabled=true;[accounts,predictions,batches,allBets,selections,aiCalls,pipelineItems,rollovers,reservations,sourceSnapshots,pushSubscriptions]=await Promise.all([
 api("strategy_accounts","select=*&order=strategy"),
 api("predictions",`predicted_at=gte.${AUDIT_LOG_START}&select=id,ai_call_id,strategy,action,confidence,reason,predicted_at,raw_response,races(id,track,race_number,race_name,start_time,surface,distance,condition,status,race_results(finish_order,confirmed_at)),bets(id,bet_type,combination,stake,odds_at_prediction,raw_estimated_probability,estimated_probability,expected_value,reason,stake_reason,settlements(return_amount,profit,is_hit,settled_at)),bet_decisions(*)&order=predicted_at.desc&limit=100`),
 api("batch_runs","select=*&order=started_at.desc&limit=30"),api("bets","select=strategy,stake,estimated_probability,settlements(return_amount,profit,is_hit)&limit=5000"),
 api("race_selections","select=race_id,batch_run_id,strategy,reason,rank,ai_call_id,created_at&order=created_at.desc&limit=500"),
 api("ai_calls",`strategy=eq.single&requested_at=gte.${AUDIT_LOG_START}&select=id,batch_run_id,purpose,strategy,provider,model,prompt_version,input_hash,output_hash,input_tokens,output_tokens,status,requested_at,completed_at,error_message&order=requested_at.desc&limit=100`),
 optionalApi("race_pipeline_items","select=id,batch_run_id,state,evidence_quality,selection_rank,selection_reason,budget_weight,initial_budget,final_budget,budget_mode,next_action_at,last_error,updated_at,races(id,track,race_number,race_name,start_time,status)&order=updated_at.desc&limit=200"),
 optionalApi("rollover_states","select=*&order=strategy"),
 optionalApi("paper_fund_reservations","select=strategy,amount,status,reserved_at&order=reserved_at.desc&limit=100"),
 optionalApi("source_data_snapshots","select=race_id,stage,source_name,identity_status,captured_at&order=captured_at.desc&limit=200"),optionalApi("push_subscriptions","select=id,endpoint&limit=20")]);lastDataAt=new Date();lastRefreshError=null;render();scrollDeepLink()}catch(e){lastRefreshError=e.message;showError(e.message);if(lastDataAt)renderDashboard()}finally{$("#refresh-data").disabled=false}}
function render(){renderOverview();renderDashboard();renderToday();renderAnalytics();renderCalls();renderOperations()}
function renderOverview(){
 const total=accounts.reduce((n,a)=>n+Number(a.current_balance)-Number(a.initial_balance),0),openReserved=reservations.filter(r=>r.status==="open").reduce((n,r)=>n+Number(r.amount),0),rollover=rollovers.find(r=>r.strategy==="single");
 $("#total-profit").textContent=`${total>=0?"+":""}${yen(total)}`;
 $("#strategy-cards").innerHTML=accounts.map(a=>{const p=Number(a.current_balance)-Number(a.initial_balance),roi=a.total_staked?Number(a.total_returned)/Number(a.total_staked)*100:0,available=Math.max(0,Number(a.current_balance)-openReserved);return `<article class="card strategy-link" data-open-strategy="${a.strategy}"><div class="card-top"><span class="badge ${a.strategy}">${labels[a.strategy]}</span><span>予想・履歴を見る →</span></div><small>利用可能なペーパー資金</small><strong>${yen(available)}</strong><div class="stats"><div><small>現在残高</small><b>${yen(a.current_balance)}</b></div><div><small>予約中</small><b>${yen(openReserved)}</b></div><div><small>回収率</small><b>${pct(roi)}</b></div></div></article>`}).join("");
 const max=Math.max(...accounts.map(a=>Number(a.current_balance)),1);$("#balance-bars").innerHTML=accounts.map(a=>`<div class="balance-row"><span>${labels[a.strategy]}</span><i><b class="${a.strategy}" style="width:${Math.max(3,Number(a.current_balance)/max*100)}%"></b></i><strong>${yen(a.current_balance)}</strong></div>`).join("")+`<div class="rollover-row"><span>複勝ころがし</span><strong>${yen(rollover?.pending_amount||0)}</strong><small>${Number(rollover?.consecutive_hits||0)}連続的中</small></div>`;
 renderPipelineSummary();
 const latest=batches[0];$("#last-run").textContent=latest?`最終実行 ${dt(latest.started_at)}`:"実行履歴なし";$("#job-list").innerHTML=batches.slice(0,4).map(b=>`<div class="job"><i>${b.status==="succeeded"?"✓":"•"}</i><div><b>${b.target_date} / ${esc(b.parser_version)}</b><small>${b.races_fetched}レース・API ${b.api_requests}回</small></div><em class="status ${b.status}">${b.status}</em></div>`).join("")||empty("実行履歴はありません")
}
function renderPipelineSummary(){
 const latestBatch=batches[0],items=latestBatch?pipelineItems.filter(x=>x.batch_run_id===latestBatch.id):[];
 const raceIds=new Set(items.map(x=>x.races?.id).filter(Boolean)),count=states=>items.filter(x=>states.includes(x.state)).length,sources=[...new Set(sourceSnapshots.filter(x=>raceIds.has(x.race_id)).map(x=>x.source_name))],failed=items.filter(x=>x.state==="failed"||x.state==="invalid_output").length;
 const steps=[{name:"Stage 1通過",value:count(["evidence_pending","evidence_ready","evidence_insufficient","selected","not_selected","final_refresh_pending","final_decided","completed"])},{name:"外部情報準備",value:count(["evidence_ready","selected","not_selected","final_refresh_pending","final_decided","completed"])},{name:"Gemini選定",value:count(["selected","final_refresh_pending","final_decided","completed"])},{name:"最終判断",value:count(["final_decided","completed"])}];
 $("#pipeline-summary").innerHTML=`<article class="panel pipeline-panel"><div class="panel-title"><h2>最新の予測フロー</h2><span>${failed?`処理エラー ${failed}件`:"正常"}</span></div><div class="pipeline-steps">${steps.map((s,i)=>`<div><small>0${i+1}</small><b>${s.name}</b><strong>${s.value}</strong><span>レース</span></div>`).join("")}</div><div class="source-strip"><b>取得元</b>${sources.length?sources.map(s=>`<span>${esc(s)}</span>`).join(""):`<span>対象レースの情報待ち</span>`}</div></article>`;
}
const activeStates=["stage1_pending","evidence_pending","evidence_ready","selected","final_refresh_pending","invalid_output"];
function clock(v){return new Date(v).toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"})}
function countdown(v){const target=Date.parse(v);if(!Number.isFinite(target))return "時刻調整中";const ms=target-Date.now();if(ms<=0)return "まもなく";const mins=Math.ceil(ms/60000);return mins<60?`あと${mins}分`:`あと${Math.floor(mins/60)}時間${String(mins%60).padStart(2,"0")}分`}
function delayLabel(v,grace=60000){const target=Date.parse(v);if(!Number.isFinite(target)||Date.now()<=target+grace)return "";return `${Math.floor((Date.now()-target)/60000)}分遅延`}
function untilRefresh(){if(!lastDataAt)return "更新待ち";const elapsed=Date.now()-lastDataAt.getTime(),left=Math.max(0,180000-elapsed);return left?`次回まで ${Math.ceil(left/1000)}秒`:"更新中"}
function reasonPoints(value){const text=String(value||"").trim();if(!text)return [];return text.split(/[。\n]|(?=・)/).map(x=>x.replace(/^・/,"").trim()).filter(Boolean).slice(0,3)}
function predictionMarks(p){const source=Array.isArray(p?.raw_response?.ranking)?p.raw_response.ranking:p?.raw_response?.predicted_top3,rows=Array.isArray(source)?source.slice().sort((a,b)=>Number(a.rank)-Number(b.rank)).slice(0,3):[];if(rows.length!==3)return "";const marks=["◎","○","▲"],labels=["1着予想","2着予想","3着予想"];return `<section class="prediction-board" aria-label="AI着順予想"><div class="prediction-board-title"><b>AI着順予想</b><small>全出走馬を比較</small></div><div class="prediction-marks">${rows.map((x,i)=>`<div class="mark-${i+1}"><span aria-label="${labels[i]}">${marks[i]}</span><b><em>${Number(x.horse_number)}</em><strong>${esc(x.horse_name||"馬名未取得")}</strong></b><small>${labels[i]}${x.reason?`・${esc(x.reason)}`:""}</small></div>`).join("")}</div></section>`}
function renderDashboard(){
 const today=jst(new Date()),latest=batches.find(b=>b.target_date===today),todayItems=latest?pipelineItems.filter(x=>x.batch_run_id===latest.id&&x.races?.start_time&&jst(x.races.start_time)===today):[],todayPreds=predictions.filter(p=>p.races?.start_time&&jst(p.races.start_time)===today&&(!latest||aiCalls.find(c=>c.id===p.ai_call_id)?.batch_run_id===latest.id)),purchased=todayPreds.filter(p=>p.action==="bet"&&(p.bets||[]).length),results=purchased.filter(p=>(p.bets||[]).length&&(p.bets||[]).every(settlementOf));
 const awaiting=x=>activeStates.includes(x.state)&&Date.parse(x.races?.start_time)>Date.now(),active=todayItems.filter(awaiting),failed=todayItems.filter(x=>x.state==="failed"||x.state==="invalid_output"),insufficient=todayItems.filter(x=>x.state==="evidence_insufficient"),total=todayItems.length,scheduledStart=Date.parse(`${today}T07:10:00+09:00`),batchMissing=!latest&&Date.now()>scheduledStart,batchFailed=latest?.status==="failed",operationalIssue=batchMissing||batchFailed;
 const actionable=todayItems.filter(x=>x.next_action_at&&Date.parse(x.races?.start_time)>Date.now()&&["selected","final_refresh_pending","invalid_output"].includes(x.state)).sort((a,b)=>Date.parse(a.next_action_at)-Date.parse(b.next_action_at)),next=actionable[0];
 const dueAt=latest?.metadata?.selection_due_at,due=Date.parse(dueAt||""),beforeEvidence=Number.isFinite(due)&&Date.now()<due,stage1Pending=todayItems.filter(x=>x.state==="stage1_pending").length,evidencePending=todayItems.filter(x=>x.state==="evidence_pending").length,evidenceReady=todayItems.filter(x=>x.state==="evidence_ready").length,evidenceEligible=todayItems.filter(x=>x.state!=="stage1_rejected"&&x.state!=="stage1_pending").length,evidenceDone=todayItems.filter(x=>["evidence_ready","evidence_insufficient","selected","not_selected","final_refresh_pending","final_decided","completed","invalid_output"].includes(x.state)).length,selected=todayItems.filter(x=>["selected","final_refresh_pending","final_decided","completed","invalid_output"].includes(x.state)).length;
 const noMeeting=latest?.status==="succeeded"&&latest?.metadata?.reason==="no_jra_races",phase=lastRefreshError?{tone:"warning",icon:"!",label:"最新状態を取得できません",copy:`最終取得 ${lastDataAt?clock(lastDataAt):"なし"}・通信状態を確認してください`}:operationalIssue?{tone:"warning",icon:"!",label:batchFailed?"本日の処理が失敗":"本日の処理が未開始",copy:batchFailed?esc(latest.error_message||"実行履歴で原因を確認してください"):"07:10を過ぎても当日バッチが作成されていません"}:failed.length?{tone:"warning",icon:"!",label:"自動処理でエラーが発生",copy:`${failed.length}件を安全停止しました。下の処理状況欄に原因を表示しています`}:stage1Pending?{tone:"working",icon:"↻",label:"一次判定を実行中",copy:`${total-stage1Pending}/${total}レースの一次判定が完了しています`}:evidencePending&&beforeEvidence?{tone:"idle",icon:"○",label:"外部情報の取得開始待ち",copy:`${clock(dueAt)}から対象${evidencePending}レースの外部情報を順番に取得します`}:evidencePending?{tone:"working",icon:"↻",label:"外部情報を収集中",copy:`${evidenceDone}/${evidenceEligible}レースの取得が完了しています`}:evidenceReady?{tone:"working",icon:"◎",label:"候補レースを選定中",copy:`外部情報を取得した${evidenceReady}レースを比較しています`}:active.some(x=>x.state==="selected")?{tone:"working",icon:"◎",label:"直前判断を待機中",copy:`選定済み${active.filter(x=>x.state==="selected").length}レース`}:latest?.status==="running"?{tone:"working",icon:"↻",label:"予測フローを実行中",copy:"次の処理を自動で開始します"}:noMeeting?{tone:"complete",icon:"✓",label:"本日はJRA開催なし",copy:"開催情報の確認は完了しています"}:total?{tone:"complete",icon:"✓",label:"本日の予測処理は完了",copy:`${total}レースを確認しました`}:{tone:"idle",icon:"○",label:"開催情報を待っています",copy:"開催日は07:00から自動で処理します"};
 const systemPending=stage1Pending||evidencePending||evidenceReady,nextAt=next?.next_action_at||(systemPending?dueAt:null),nextDelay=next?delayLabel(nextAt):"",nextLabel=next?`${esc(next.races.track)} ${next.races.race_number}R 直前更新`:lastRefreshError?"データを再読み込み":evidencePending&&beforeEvidence?"外部情報の取得を開始":evidencePending?"外部情報の取得を継続":evidenceReady?"候補レースを選定":operationalIssue?"実行履歴を確認":noMeeting?"次回開催日の07:00に確認":"次の予定はありません";
 const visibleOperationalIssue=operationalIssue&&!lastRefreshError,issueCount=failed.length+(lastRefreshError?1:0)+(visibleOperationalIssue?1:0);$("#dashboard-command").innerHTML=`<section class="command-card status-board ${phase.tone}"><div class="command-status"><span class="command-icon">${phase.icon}</span><div><p class="eyebrow">CURRENT STATUS</p><h2>${phase.label}</h2><p>${phase.copy}</p></div></div><div class="status-metrics"><div><small>本日の登録</small><strong class="${total>36?"metric-alert":""}">${total}<em>/ 36</em></strong><span>レース</span></div><div><small>一次判定</small><strong>${total-stage1Pending}<em>/ ${total||36}</em></strong><span>${stage1Pending?"処理中":total?"完了":"未開始"}</span></div><div><small>外部情報</small><strong>${evidenceDone}<em>/ ${evidenceEligible}</em></strong><span>${evidencePending?(beforeEvidence?"開始待ち":"取得中"):evidenceEligible?"完了":"対象なし"}</span></div><div><small>候補選定</small><strong>${selected}</strong><span>${selected?"選定済み":evidencePending||evidenceReady?"選定前":"対象なし"}</span></div><div class="${issueCount?"metric-error":"metric-ok"}"><small>エラー</small><strong>${issueCount}</strong><span>${issueCount?"要確認":"正常"}</span></div></div><div class="next-action"><small>次に起きること</small>${next?`<button class="next-action-link" data-scroll-race="${next.races.id}"><strong>${clock(nextAt)} ${nextLabel}</strong><b>候補を見る →</b></button>`:`<strong>${nextAt?`${clock(nextAt)} ${nextLabel}`:nextLabel}</strong>`}<span class="${nextDelay?"late":""}">${nextDelay||(nextAt?countdown(nextAt):noMeeting?"確認完了":visibleOperationalIssue?"要確認":"自動運転中")}</span></div></section>`;
 renderDashboardTimeline(todayItems,todayPreds,latest);
 $("#purchased-count").textContent=`購入 ${purchased.length}・確定 ${results.length}`;
 $("#dashboard-races").innerHTML=purchased.length?purchased.sort((a,b)=>Date.parse(b.races.start_time)-Date.parse(a.races.start_time)).map(dashboardRaceCard).join(""):empty("本日購入したレースはまだありません");
 $("#dashboard-alerts").innerHTML=`<article class="panel compact-panel alert-panel ${issueCount||insufficient.length?"has-alert":""}"><div class="panel-title"><h2>処理状況</h2><span>${issueCount?`要確認 ${issueCount}件`:insufficient.length?`情報不足 ${insufficient.length}件`:"問題なし"}</span></div>${lastRefreshError?`<div class="alert-row"><b>データ更新に失敗</b><span>通信</span><small>${esc(lastRefreshError)}</small></div><button class="retry-button" data-refresh-now>今すぐ再読み込み</button>`:""}${visibleOperationalIssue?`<div class="alert-row"><b>${batchFailed?"当日バッチが失敗":"当日バッチが未開始"}</b><span>運用</span><small>${esc(latest?.error_message||"実行履歴とスケジュールを確認してください")}</small></div>`:""}${failed.slice(0,3).map(x=>`<div class="alert-row"><b>${esc(x.races?.track||"")} ${x.races?.race_number||""}R</b><span>${stateLabels[x.state]||x.state}</span><small>${esc(x.last_error||"自動処理を安全停止しました")}</small></div>`).join("")}${!issueCount&&insufficient.length?`<div class="alert-row"><b>外部情報が不足</b><span>${insufficient.length}レース</span><small>候補選定の対象外として安全に処理しました</small></div>`:""}${!issueCount&&!insufficient.length?`<div class="all-clear"><span>✓</span><div><b>正常に稼働しています</b><small>エラーや情報不足はありません</small></div></div>`:""}<button class="alert-link" data-page-target="operations">${issueCount||insufficient.length?"処理履歴で詳細を見る":"処理履歴を見る"} →</button></article>`;
 const stake=purchased.flatMap(p=>p.bets||[]).reduce((n,b)=>n+Number(b.stake),0),returned=purchased.flatMap(p=>p.bets||[]).reduce((n,b)=>n+Number(settlementOf(b)?.return_amount||0),0),settled=purchased.length>0&&purchased.every(p=>(p.bets||[]).every(settlementOf));
 $("#dashboard-money").innerHTML=`<div class="money-grid"><div><small>投資</small><b>${yen(stake)}</b></div><div><small>払戻</small><b>${yen(returned)}</b></div><div class="money-profit"><small>${settled?"確定損益":"現在損益"}</small><strong class="${returned-stake>=0?"positive":"negative"}">${returned-stake>=0?"+":""}${yen(returned-stake)}</strong></div></div>`;
 renderNotificationControl();
}
function renderNotificationControl(){const supported="serviceWorker" in navigator&&"PushManager" in window&&"Notification" in window,enabled=supported&&pushSubscriptions.length>0&&Notification.permission==="granted";$("#dashboard-notifications").innerHTML=`<article class="panel compact-panel notification-panel ${enabled?"enabled":""}"><span class="notification-icon">${enabled?"✓":"♧"}</span><div><small>的中通知</small><b>${enabled?"通知オン":"通知オフ"}</b><p>${supported?enabled?"的中したレースの結果だけ通知します":"外れや予想開始は通知しません":"このブラウザはWeb Pushに対応していません"}</p></div>${supported?`<button data-push-toggle>${enabled?"解除":"通知を受け取る"}</button>`:""}</article>`}
function urlBase64ToUint8Array(value){const padding="=".repeat((4-value.length%4)%4),base64=(value+padding).replace(/-/g,"+").replace(/_/g,"/"),raw=atob(base64);return Uint8Array.from([...raw].map(x=>x.charCodeAt(0)))}
async function togglePush(){const button=$("[data-push-toggle]");if(button)button.disabled=true;try{const registration=await navigator.serviceWorker.ready,current=await registration.pushManager.getSubscription();if(current){await apiWrite("push_subscriptions","DELETE",`endpoint=eq.${encodeURIComponent(current.endpoint)}`);await current.unsubscribe();pushSubscriptions=pushSubscriptions.filter(x=>x.endpoint!==current.endpoint);renderNotificationControl();return}const permission=await Notification.requestPermission();if(permission!=="granted")throw new Error("通知が許可されませんでした");const response=await fetch(`${SUPABASE_URL}/functions/v1/push-config`,{headers:{apikey:SUPABASE_KEY}}),config=await response.json();if(!response.ok)throw new Error(config.error==="PUSH_NOT_CONFIGURED"?"通知用キーが未設定です":config.error||"通知設定を取得できません");const subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(config.publicKey)}),json=subscription.toJSON();if(!json.keys?.p256dh||!json.keys?.auth)throw new Error("ブラウザの通知購読情報を取得できません");await apiWrite("push_subscriptions","POST","on_conflict=user_id,endpoint",{user_id:session.user.id,endpoint:subscription.endpoint,p256dh:json.keys.p256dh,auth:json.keys.auth,user_agent:navigator.userAgent,updated_at:new Date().toISOString()});pushSubscriptions=[...pushSubscriptions,{endpoint:subscription.endpoint}];renderNotificationControl()}catch(error){showError(error.message);renderNotificationControl()}}
function scrollDeepLink(){const raceId=new URLSearchParams(location.search).get("race");if(!raceId)return;setTimeout(()=>document.querySelector(`#result-race-${CSS.escape(raceId)}`)?.scrollIntoView({behavior:"smooth",block:"center"}),100)}
function legacyRenderDashboardTimeline(items,todayPreds,batch){
 const counts=s=>items.filter(x=>s.includes(x.state)).length,selectionDue=batch?.metadata?.selection_due_at;
 const systemSteps=[
  {time:"07:00",label:"開催情報を取得",sub:items.length?`${items.length}レースを登録`:"開催確認",done:!!items.length},
  {time:selectionDue?clock(selectionDue):"09:00",label:"候補レースを選定",sub:counts(["evidence_pending"])?`${counts(["evidence_pending"])}レースの情報を収集中`:`Geminiの選定まで完了`,active:counts(["stage1_pending","evidence_pending","evidence_ready"])>0,done:items.length&&!counts(["stage1_pending","evidence_pending","evidence_ready"])}
 ];
 const byRace=new Map(todayPreds.map(p=>[p.races?.id,p])),focus=items.filter(x=>["selected","final_refresh_pending","final_decided","completed","invalid_output","failed"].includes(x.state)||byRace.has(x.races?.id));
 todayPreds.forEach(p=>{if(!focus.some(x=>x.races?.id===p.races?.id))focus.push({state:"completed",next_action_at:null,races:p.races})});
 focus.sort((a,b)=>Date.parse(a.next_action_at||byRace.get(a.races?.id)?.predicted_at||a.races.start_time)-Date.parse(b.next_action_at||byRace.get(b.races?.id)?.predicted_at||b.races.start_time));
 const races=focus.map(item=>raceTimelineCard(item,byRace.get(item.races?.id))).join("");
 $("#dashboard-timeline").innerHTML=`<section class="dashboard-section timeline-section"><div class="section-heading"><div><p class="eyebrow">TODAY'S FLOW</p><h2>本日のタイムライン</h2></div><div class="refresh-state ${lastRefreshError?"failed":""}"><span class="live-pill"><i></i>${lastRefreshError?"更新失敗":"自動更新中"}</span><small>最終 ${lastDataAt?clock(lastDataAt):"--:--"}・${untilRefresh()}</small></div></div><div class="now-line"><span>現在 ${clock(new Date())}</span><i></i></div><div class="visual-timeline system-timeline">${systemSteps.map((s,i)=>`<div class="timeline-item ${s.done?"done":s.active?"active":"pending"}"><div class="timeline-marker">${s.done?"✓":s.active?"●":i+1}</div><time>${s.time}</time><div><b>${s.label}</b><small>${s.sub}</small></div><em>${s.done?"完了":s.active?"進行中":"予定"}</em></div>`).join("")}</div><div class="race-timeline-heading"><b>レース別の予定と結果</b><span>判断 → 購入 → 発走 → 結果</span></div><div class="race-timelines">${races||empty("注目レースが決まると、ここに予定時刻が表示されます")}</div></section>`;
}
function raceTimelineCard(item,p){
 const r=p?.races||item.races,bets=p?.bets||[],stake=bets.reduce((n,b)=>n+Number(b.stake),0),settlements=bets.map(settlementOf).filter(Boolean),settled=bets.length&&settlements.length===bets.length,returned=settlements.reduce((n,s)=>n+Number(s.return_amount||0),0),profit=returned-stake,hit=settled&&settlements.some(s=>s.is_hit),call=p?aiCalls.find(c=>c.id===p.ai_call_id):null,decisionAt=call?.requested_at||p?.predicted_at||item.next_action_at,decisionDone=!!p,purchased=bets.length>0,incomplete=p?.action==="bet"&&!purchased,failed=item.state==="failed"||item.state==="invalid_output"||incomplete,result=Array.isArray(r.race_results)?r.race_results[0]:r.race_results,resultTimes=settlements.map(s=>s.settled_at).filter(Boolean).sort(),resultAt=resultTimes[resultTimes.length-1]||result?.confirmed_at,status=failed?"failed":settled?(hit?"hit":"miss"):p?.action==="skip"?"skipped":Date.parse(r.start_time)<=Date.now()?"checking":"upcoming";
 const savedSelection=selections.find(s=>s.race_id===r.id),selectionReason=item.selection_reason||savedSelection?.reason,selectionRank=item.selection_rank||savedSelection?.rank;
 const ticketText=bets.map(b=>`${betLabels[b.bet_type]||b.bet_type} ${(b.combination||[]).join("-")} ${yen(b.stake)}`).join(" / ");
 const events=[
  {time:decisionAt?clock(decisionAt):"--:--",label:decisionDone?"Gemini最終判断":"Gemini最終判断を開始",sub:decisionDone?(incomplete?`購入判断後の保存に失敗・信頼度 ${Number(p.confidence||0)}%`:purchased?`購入を決定・信頼度 ${Number(p.confidence||0)}%`:`見送り・信頼度 ${Number(p.confidence||0)}%`):`${countdown(decisionAt)}・発走20分前`,done:decisionDone,active:!decisionDone&&decisionAt&&Date.parse(decisionAt)<=Date.now()},
  {time:purchased?clock(p.predicted_at):"--:--",label:purchased?`${yen(stake)}分を購入`:incomplete?"購入保存エラー":decisionDone?"購入なし":"購入判断",sub:purchased?ticketText:incomplete?(item.last_error||"購入情報を保存できませんでした"):decisionDone?"AIが見送りました":"最終判断後に表示",done:decisionDone&&!incomplete,active:false},
  {time:clock(r.start_time),label:"発走",sub:Date.parse(r.start_time)>Date.now()?countdown(r.start_time):"レース終了・結果を確認中",done:Date.parse(r.start_time)<=Date.now(),active:Date.parse(r.start_time)<=Date.now()&&!settled},
  {time:resultAt?clock(resultAt):"--:--",label:settled?(hit?"結果取得・的中":"結果取得・不的中"):status==="skipped"?"結果確認の対象外":"結果取得・自動精算",sub:settled?`払戻 ${yen(returned)}・損益 ${profit>=0?"+":""}${yen(profit)}`:status==="checking"?"3分間隔で結果を確認しています":purchased?"発走後に自動取得":"購入時のみ自動精算",done:settled||status==="skipped",active:status==="checking"}
 ];
 const points=reasonPoints(selectionReason),decisionDelay=!decisionDone?delayLabel(decisionAt):"",resultDelay=purchased&&!settled&&Date.now()>Date.parse(r.start_time)+10*60000?`${Math.floor((Date.now()-Date.parse(r.start_time))/60000)}分結果待ち`:"",delayMessage=decisionDelay?`最終判断が予定から ${decisionDelay}`:resultDelay;
 return `<article id="timeline-race-${r.id}" class="race-timeline-card ${status} ${delayMessage?"delayed":""}"><div class="race-timeline-title"><div><span>${status==="failed"?"処理失敗":status==="hit"?"的中":status==="miss"?"不的中":status==="skipped"?"見送り":status==="checking"?"結果待ち":"判断予定"}</span><h3>${esc(r.track)} ${r.race_number}R</h3><small>${esc(r.race_name)}</small></div><time>${clock(r.start_time)} 発走</time></div><div class="selection-reason"><span>選定理由${selectionRank?`・優先${selectionRank}位`:""}${item.initial_budget!=null?`・初期予算 ${yen(item.initial_budget)}`:""}${item.final_budget!=null?`・最終上限 ${yen(item.final_budget)}`:""}</span>${points.length?`<ul>${points.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`:`<p>選定理由の記録はありません</p>`}</div>${p?predictionMarks(p):""}${failed?`<div class="delay-warning">${esc(item.last_error||"購入情報の保存に失敗しました")}・AIの見送りではありません</div>`:delayMessage?`<div class="delay-warning">${delayMessage}・処理履歴を確認してください</div>`:""}<div class="race-event-list">${events.map((e,i)=>`<div class="race-event ${e.done?"done":e.active?"active":"pending"}"><i>${e.done?"✓":e.active?"●":i+1}</i><time>${e.time}</time><div><b>${e.label}</b><small>${esc(e.sub)}</small></div></div>`).join("")}</div>${p?`<button class="race-log-link" data-open-call="${p.ai_call_id}">AI判断の詳細を見る <b>→</b></button>`:""}</article>`;
}
function renderDashboardTimeline(items,todayPreds,batch){
 const counts=s=>items.filter(x=>s.includes(x.state)).length,selectionDue=batch?.metadata?.selection_due_at;
 const byRace=new Map(todayPreds.map(p=>[p.races?.id,p])),focus=items.filter(x=>["selected","final_refresh_pending","final_decided","completed","invalid_output"].includes(x.state)||byRace.has(x.races?.id));
 todayPreds.forEach(p=>{if(!focus.some(x=>x.races?.id===p.races?.id))focus.push({state:"completed",next_action_at:null,races:p.races})});
 const stage1Pending=counts(["stage1_pending"]),evidencePending=counts(["evidence_pending"]),evidenceReady=counts(["evidence_ready"]),due=Date.parse(selectionDue||""),beforeEvidence=Number.isFinite(due)&&Date.now()<due,collecting=stage1Pending+evidencePending+evidenceReady,selectionDone=items.length>0&&!collecting,finalPending=counts(["selected","final_refresh_pending","invalid_output"]),purchased=todayPreds.filter(p=>p.action==="bet"&&(p.bets||[]).length),settled=purchased.filter(p=>(p.bets||[]).every(settlementOf)).length,evidenceEligible=items.filter(x=>x.state!=="stage1_rejected"&&x.state!=="stage1_pending").length,evidenceDone=items.filter(x=>["evidence_ready","evidence_insufficient","selected","not_selected","final_refresh_pending","final_decided","completed","invalid_output"].includes(x.state)).length;
 const steps=[
  {label:"開催情報",sub:items.length?`${items.length}レース登録`:"07:00に確認",done:!!items.length,active:!items.length},
  {label:"一次判定",sub:stage1Pending?`${items.length-stage1Pending}/${items.length}レース完了`:items.length?"全レース完了":"開催確認後",done:items.length>0&&!stage1Pending,active:stage1Pending>0},
  {label:"外部情報",sub:evidencePending?(beforeEvidence?`${clock(selectionDue)}から${evidencePending}レース取得`:`${evidenceDone}/${evidenceEligible}レース取得完了`):evidenceEligible?"取得完了":"対象なし",done:items.length>0&&!evidencePending&&!stage1Pending,active:evidencePending>0},
  {label:"候補選定",sub:selectionDone?`${focus.length}レース選定`:evidencePending?(beforeEvidence?"外部情報取得後":"情報取得中"):"比較処理中",done:selectionDone,active:evidenceReady>0},
  {label:"最終判断",sub:finalPending?`${finalPending}レース待機`:todayPreds.length?`${todayPreds.length}レース完了`:"発走20分前",done:selectionDone&&focus.length>0&&!finalPending,active:finalPending>0},
  {label:"結果確認",sub:purchased.length?`${settled}/${purchased.length}レース確定`:"購入時のみ",done:purchased.length>0&&settled===purchased.length,active:purchased.length>settled}
 ];
 focus.sort((a,b)=>Number(a.selection_rank||99)-Number(b.selection_rank||99)||Date.parse(a.races?.start_time)-Date.parse(b.races?.start_time));
 const candidateCards=selectionDone?focus.map(item=>raceTimelineCard(item,byRace.get(item.races?.id))).join(""):"";
 const candidateEmpty=selectionDone?empty("本日の候補レースはありません"):`<div class="selection-wait"><span>◎</span><div><b>候補レースはまだ決まっていません</b><p>${evidencePending&&beforeEvidence?`${clock(selectionDue)}から外部情報を取得し、完了後に候補を選定します。`:evidencePending?`外部情報を取得中です（${evidenceDone}/${evidenceEligible}レース完了）。`:"外部情報の取得完了後に候補を選定します。"}</p></div></div>`;
 $("#dashboard-timeline").innerHTML=`<section class="dashboard-section flow-section"><div class="section-heading"><div><p class="eyebrow">TODAY'S FLOW</p><h2>本日の進行状況</h2></div><div class="refresh-state ${lastRefreshError?"failed":""}"><span class="live-pill"><i></i>${lastRefreshError?"更新失敗":"自動更新中"}</span><small>最終 ${lastDataAt?clock(lastDataAt):"--:--"}・${untilRefresh()}</small></div></div><div class="flow-steps">${steps.map((s,i)=>`<div class="flow-step ${s.done?"done":s.active?"active":"pending"}"><i>${s.done?"✓":i+1}</i><div><b>${s.label}</b><small>${s.sub}</small></div></div>`).join("")}</div><div class="candidate-heading"><div><p class="eyebrow">SHORTLIST</p><h3>候補レース</h3></div><span>${selectionDone?`${focus.length}レース`:"選定前"}</span></div><div class="race-timelines">${candidateCards||candidateEmpty}</div></section>`;
}
function dashboardRaceCard(p){
 const r=p.races,bets=p.bets||[],settled=bets.length&&bets.every(settlementOf),returned=bets.reduce((n,b)=>n+Number(settlementOf(b)?.return_amount||0),0),stake=bets.reduce((n,b)=>n+Number(b.stake),0),hit=settled&&bets.some(b=>settlementOf(b)?.is_hit),result=Array.isArray(r.race_results)?r.race_results[0]:r.race_results,state=settled?(hit?"hit":"miss"):Date.parse(r.start_time)<=Date.now()?"checking":"purchased",label=settled?(hit?"的中":"不的中"):state==="checking"?"結果確認中":"購入済み";
 return `<article id="result-race-${r.id}" class="dashboard-race ${state}"><div class="race-state"><span>${label}</span><time>${state==="purchased"?countdown(r.start_time):settled?`損益 ${returned-stake>=0?"+":""}${yen(returned-stake)}`:"3分間隔で確認"}</time></div><div class="dashboard-race-head"><div><small>${clock(r.start_time)} 発走</small><h3>${esc(r.track)} ${r.race_number}R</h3><p>${esc(r.race_name)}</p></div>${result?`<div class="finish-order"><small>確定着順</small><b>${result.finish_order.slice(0,3).join(" — ")}</b></div>`:""}</div>${predictionMarks(p)}<div class="result-evaluation"><span>AI信頼度 <b>${Number(p.confidence||0)}%</b></span><span>結果 <b>${settled?(hit?"的中":"不的中"):"待機中"}</b></span><span>損益 <b class="${settled?(returned-stake>=0?"positive":"negative"):""}">${settled?`${returned-stake>=0?"+":""}${yen(returned-stake)}`:"未確定"}</b></span></div><div class="ticket-list">${bets.map(b=>{const s=settlementOf(b);return `<div><b>${betLabels[b.bet_type]||b.bet_type} ${(b.combination||[]).join("-")}</b><span>${yen(b.stake)}</span><em class="${s?.is_hit?"positive":s?"negative":""}">${s?(s.is_hit?`払戻 ${yen(s.return_amount)}`:"外れ"):"結果待ち"}</em></div>`}).join("")}</div><button class="race-log-link" data-open-call="${p.ai_call_id}">AIがこの判断をした理由 <b>→</b></button></article>`
}
function renderToday(){const ids=Object.keys(labels);$("#strategy-tabs").innerHTML=ids.map(x=>`<button class="${x===activeStrategy?"active":""}" data-strategy="${x}">${labels[x]}</button>`).join("");const list=predictions.filter(p=>p.strategy===activeStrategy),today=jst(new Date()),now=list.filter(p=>jst(p.races.start_time)===today),past=list.filter(p=>jst(p.races.start_time)!==today);$("#race-list").innerHTML=group("本日の予想",now,"本日の予想はまだありません")+group("過去の履歴",past,"過去の履歴はありません")}
function group(title,items,msg){return `<section class="race-group"><div class="race-group-title"><h2>${title}</h2><span>${items.length}レース</span></div>${items.length?items.map(raceCard).join(""):empty(msg)}</section>`}
function raceCard(p){const r=p.races,bets=p.bets||[],decisions=p.bet_decisions||[],incomplete=p.action==="bet"&&!bets.length,stake=bets.reduce((n,b)=>n+Number(b.stake),0),returned=bets.reduce((n,b)=>n+Number(settlementOf(b)?.return_amount||0),0);return `<article class="race"><div class="race-heading"><div><small>${new Date(r.start_time).toLocaleDateString("ja-JP")}・${r.surface==="turf"?"芝":"ダート"} ${r.distance||"—"}m</small><div><strong>${esc(r.track)} ${r.race_number}R</strong><span>${esc(r.race_name)}</span></div></div><span class="outcome ${incomplete?"failed":p.action}">${incomplete?"購入保存エラー":p.action==="bet"?"ペーパーBET":"AI見送り"}</span></div>${incomplete?`<div class="delay-warning">購入判断後の保存に失敗しました。AIの見送りではありません。</div>`:""}<div class="prediction-meta"><span>Gemini信頼度 ${Number(p.confidence||0)}%</span><span>T-20情報で判断</span></div>${predictionMarks(p)}<p class="race-copy">${esc(p.reason)}</p>${bets.map(b=>`<div class="bet"><b>${betLabels[b.bet_type]||b.bet_type} ${b.combination.join("-")}</b><span>${yen(b.stake)}</span><small>予測時オッズ ${Number(b.odds_at_prediction).toFixed(1)}${b.expected_value==null?"":` / 参考EV ${Number(b.expected_value).toFixed(2)}`}</small></div>`).join("")}<div class="decision-link" data-open-call="${p.ai_call_id}">Geminiへの入力と判断根拠を見る <b>→</b></div><div class="race-result"><span>投資 ${yen(stake)}</span><span>払戻 ${r.status==="finished"?yen(returned):"—"}</span><span>技術検証 ${decisions.length}件</span></div></article>`}
function renderAnalytics(){const stats=accounts.map(a=>({...a,...RaceAnalytics.strategyStats(allBets,a.strategy)})),tot=RaceAnalytics.validationStats(allBets);$("#analysis-metrics").innerHTML=[["検証済み馬券",tot.count],["確率誤差",pct(tot.calibrationGap*100)],["Brierスコア",tot.brierScore.toFixed(3)],["AI処理履歴",aiCalls.length]].map(x=>`<div class="metric"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join("");$("#analysis-table").innerHTML=stats.map(a=>`<tr><td><span class="badge ${a.strategy}">${labels[a.strategy]}</span></td><td>${yen(a.staked)}</td><td>${yen(a.returned)}</td><td class="${a.profit>=0?"positive":"negative"}">${yen(a.profit)}</td><td>${pct(a.roi)}</td><td>${pct(a.predictedRate*100)}</td><td>${pct(a.observedRate*100)}</td><td>${pct(a.calibrationGap*100)}</td><td>${a.brierScore.toFixed(3)}</td></tr>`).join("")}
function filteredCalls(){const purpose=$("#trace-purpose").value,strategy=$("#trace-strategy").value;return aiCalls.filter(c=>(purpose==="all"||c.purpose===purpose)&&(strategy==="all"||c.strategy===strategy))}
function renderCalls(){const rows=filteredCalls(),names={screening:"候補レースを選定",prediction:"最終判断",correction:"回答を再確認",audit:"監査"};$("#call-list").innerHTML=rows.map(c=>{const related=predictions.filter(p=>p.ai_call_id===c.id),race=related[0]?.races,bets=related.flatMap(p=>p.bets||[]),incomplete=related.some(p=>p.action==="bet"&&!(p.bets||[]).length),action=incomplete?"保存失敗":bets.length?"購入":related.length?"見送り":names[c.purpose]||c.purpose;return `<button class="call-item ${selectedCall===c.id?"active":""}" data-ai-call="${c.id}"><span><em class="decision-chip ${incomplete?"failed":bets.length?"buy":related.length?"skip":"process"}">${action}</em><time>${clock(c.requested_at)}</time></span><strong>${race?`${esc(race.track)} ${race.race_number}R`:names[c.purpose]||c.purpose}</strong><small class="call-race-name">${race?esc(race.race_name):c.purpose==="screening"?"本日の全レースを比較":"Gemini AI処理"}</small><small>${c.status==="succeeded"?"✓ AI応答完了":"処理状態: "+esc(c.status)}・${Number(c.input_tokens||0).toLocaleString()} tokens</small></button>`}).join("")||empty("条件に一致するAI処理はありません")}
function modelAnswer(response){const text=response?.candidates?.[0]?.content?.parts?.map(p=>p.text).filter(Boolean).join("\n");if(!text)return null;try{return JSON.parse(text)}catch{return text}}
function promptPayload(prompt){const value=String(prompt||""),marker="INPUT_JSON=" ,at=value.lastIndexOf(marker);if(at>=0){try{return JSON.parse(value.slice(at+marker.length))}catch{}}for(let i=value.length-1;i>=0;i--){if(value[i]!=="["&&value[i]!=="{")continue;try{return JSON.parse(value.slice(i))}catch{}}return null}
function inputView(call){const payload=promptPayload(call.request_json?.prompt);if(!payload)return `<div class="legacy-note">入力データを読み取れませんでした。</div>`;if(call.purpose==="screening"){const rows=Array.isArray(payload)?payload:(payload.races||[]);return `<div class="input-summary"><span><b>${rows.length}</b>件を比較</span><span><b>単勝</b>市場人気を確認</span></div><div class="data-grid">${rows.map(screeningInputCard).join("")}</div>`}const rows=Array.isArray(payload)?payload:[payload];return rows.map(r=>raceInputCard(r)).join("")}
function screeningInputCard(row){const race=row.race||row,market=row.market||{},runners=market.runners||[],roughness=(row.evidence||[]).find(x=>x.source==="uma-x")?.raceMetrics?.roughness;return `<article class="data-card"><b>${esc(race.track||"分析結果")} ${race.race_number||race.raceNumber||""}R</b><strong>${esc(race.race_name||race.raceName||row.race_id||"")}</strong><small>${race.surface==="turf"?"芝":race.surface==="dirt"?"ダート":esc(race.surface||"")} ${race.distance?`・${race.distance}m`:""}</small><small>市場人気：${market.status==="available"?`${runners.length}頭・${esc(market.captured_at||"")}`:"取得不可"}</small>${runners.length?`<small>上位 ${runners.slice(0,4).map(x=>`${x.popularity||"—"}人気 ${x.horse_number}番 ${Number(x.win_odds).toFixed(1)}倍`).join(" / ")}</small>`:""}${roughness?`<small>ウマークス荒度 ${roughness}/18（オッズ由来）</small>`:""}</article>`}
function raceInputCard(row){const race=row.race||{},entries=race.entries||row.entries||[],evals=row.independent_evaluation?.evaluations||row.evaluations||[],odds=row.valid_market_odds||row.odds||[],byNumber=new Map(entries.map(e=>[e.horseNumber,e])),budget=row.wager_budget||{};return `<article class="input-race"><div class="input-race-head"><div><b>${esc(race.track)} ${race.raceNumber||race.race_number||""}R</b><strong>${esc(race.raceName||race.race_name||"")}</strong></div><span>${race.surface==="turf"?"芝":race.surface==="dirt"?"ダート":esc(race.surface||"—")} ${race.distance||"—"}m</span></div>${budget.maximum_total_stake!=null?`<div class="input-summary"><span><b>${yen(budget.maximum_total_stake)}</b>今回の上限</span><span><b>${esc(row.capital_context?.capital_mode||"normal")}</b>資金モード</span></div>`:""}<h4>過去走から整理した参考評価</h4><div class="table-wrap compact"><table><thead><tr><th>馬</th><th>総合</th><th>能力</th><th>適性</th><th>状態</th><th>展開</th><th>推定勝率</th><th>品質</th></tr></thead><tbody>${evals.sort((a,b)=>b.overallScore-a.overallScore).map(e=>{const entry=byNumber.get(e.horseNumber)||{};return `<tr><td><b>${e.horseNumber} ${esc(e.horseName||entry.horseName)}</b><small>${esc(entry.jockey||"")}</small></td><td><strong>${Number(e.overallScore).toFixed(1)}</strong></td><td>${Number(e.abilityScore).toFixed(1)}</td><td>${Number(e.suitabilityScore).toFixed(1)}</td><td>${Number(e.conditionScore).toFixed(1)}</td><td>${Number(e.raceContextScore).toFixed(1)}</td><td>${pct(Number(e.estimatedWinProbability)*100)}</td><td>${pct(Number(e.dataQuality)*100)}<small>${e.sampleSize}走</small></td></tr>`}).join("")}</tbody></table></div><details><summary>AIが比較した有効オッズ ${odds.length}件</summary><div class="odds-grid">${odds.map(o=>`<span><b>${betLabels[o.type]||o.type} ${(o.horses||[]).join("-")}</b>${Number(o.odds).toFixed(1)}${o.oddsMax?`〜${Number(o.oddsMax).toFixed(1)}`:""}倍${o.popularity?`・${o.popularity}人気`:""}</span>`).join("")}</div></details></article>`}
async function openCall(id){selectedCall=id;renderCalls();const el=$("#trace-detail");el.innerHTML='<div class="loading">監査データを読み込んでいます…</div>';try{const [callRows,preds]=await Promise.all([api("ai_calls",`id=eq.${encodeURIComponent(id)}&select=*`),api("predictions",`ai_call_id=eq.${encodeURIComponent(id)}&select=id,strategy,action,confidence,reason,raw_response,races(id,track,race_number,race_name,start_time),bets(*),bet_decisions(*)&order=predicted_at`)]),call=callRows[0];if(!call)throw new Error("AI処理が見つかりません");renderTrace(call,preds)}catch(e){el.innerHTML=empty(e.message)}}
function renderTrace(call,preds){const answer=modelAnswer(call.response_json),decisions=preds.flatMap(p=>(p.bet_decisions||[]).map(d=>({...d,race:p.races,prediction:p}))),purchased=decisions.filter(d=>d.decision!=="rejected").length,rejected=decisions.filter(d=>d.decision==="rejected").length,bets=preds.flatMap(p=>p.bets||[]),primary=preds[0],selection=primary?(pipelineItems.find(x=>x.races?.id===primary.races.id)||selections.find(x=>x.race_id===primary.races.id)):null,selectionReason=selection?.selection_reason||selection?.reason,verdict=bets.length?"購入":preds.length?"見送り":"候補を選定";$("#trace-detail").innerHTML=`<div class="trace-title"><div><span class="decision-chip ${bets.length?"buy":preds.length?"skip":"process"}">${verdict}</span><h2>${primary?`${esc(primary.races.track)} ${primary.races.race_number}R ${esc(primary.races.race_name)}`:call.purpose==="prediction"?"発走前の最終判断":"本日の候補レース選定"}</h2><p>${dt(call.requested_at)}・Geminiによる判断</p></div><div class="trace-summary"><b>${purchased}</b><small>購入</small><b>${rejected}</b><small>AI見送り</small></div></div>
<section class="decision-overview"><div><p class="eyebrow">DECISION</p><h3>${bets.length?`${bets.length}点を購入`:preds.length?"このレースは見送り":"対象レースを絞り込み"}</h3><p>${primary?esc(primary.reason):"全レースを比較し、直前判断へ進める候補を選びました。"}</p></div>${primary?`<div class="confidence-ring" style="--confidence:${Number(primary.confidence||0)*3.6}deg"><strong>${Number(primary.confidence||0)}<small>%</small></strong><span>信頼度</span></div>`:""}${primary?predictionMarks(primary):""}${bets.length?`<div class="overview-tickets">${bets.map(b=>`<span><b>${betLabels[b.bet_type]||b.bet_type} ${(b.combination||[]).join("-")}</b>${yen(b.stake)}</span>`).join("")}</div>`:""}</section>
${primary?`<section class="reason-comparison"><div><small>候補に選んだ理由</small><b>${esc(selectionReason||"選定理由の記録なし")}</b></div><span>→</span><div><small>直前の最終判断</small><b>${esc(primary.reason||"最終判断理由の記録なし")}</b></div></section>`:""}
<div class="detail-divider"><span>詳しい判断過程</span></div>
<section class="trace-step"><div class="step-no">1</div><div><p class="eyebrow">AI INPUT</p><h3>AIに渡したデータ</h3><p>対象レース、出走馬の評価、予測確率、データ品質、オッズを読みやすく整理しています。</p><div class="hashes"><span>対象データ改ざん検知済み</span><span>${Number(call.input_tokens||0).toLocaleString()} tokens</span></div>${inputView(call)}</div></section>
<section class="trace-step"><div class="step-no">2</div><div><p class="eyebrow">AI RESPONSE</p><h3>AIの回答</h3>${renderAnswer(answer,preds)}</div></section>
<section class="trace-step"><div class="step-no">3</div><div><p class="eyebrow">SYSTEM GUARD</p><h3>購入条件の確認</h3><p>プログラムはAIの予想を作り直しません。実在する馬・対応券種・100円単位・残高・正常オッズに加え、複数点的中時を含む回収割れがないかを確認します。</p>${decisions.length?decisions.map(decisionCard).join(""):`<div class="legacy-note">${call.purpose==="screening"?"この処理はレース候補の選定です。最終判断は発走約20分前にGeminiが行います。":"Geminiはこのレースを見送りました。"}</div>`}</div></section>
<section class="trace-step final"><div class="step-no">4</div><div><p class="eyebrow">FINAL RESULT</p><h3>最終結果</h3>${preds.length?preds.map(p=>`<div class="final-row"><b>${esc(p.races.track)} ${p.races.race_number}R ${esc(p.races.race_name)}</b><span>${p.action==="bet"&&(p.bets||[]).length?`${p.bets.length}点・${yen(p.bets.reduce((n,b)=>n+Number(b.stake),0))}`:"見送り"}</span></div>`).join(""):"後続の予測処理で購入を決定します。"}</div></section>`}
function renderAnswer(a,preds){if(!a)return `<div class="legacy-note">Geminiから有効な回答を取得できませんでした。</div>`;if(typeof a==="string")return `<div class="legacy-note">${esc(a)}</div>`;if(Array.isArray(a.assessments)){const chosen=a.assessments.filter(x=>x.selected);return `<div class="answer-box"><div><small>AIが選んだレース</small><strong>${chosen.length}件</strong></div><div><small>全体判断</small><strong>${esc(a.overall_reason||"—")}</strong></div></div>${a.assessments.sort((x,y)=>(x.selected?0:1)-(y.selected?0:1)||Number(x.priority||99)-Number(y.priority||99)).map(x=>`<div class="selection-answer"><span class="badge single">${x.selected?`選択 ${x.priority}`:"非選択"}</span><b>${esc(x.race_id)}</b><strong>予算比率 ${Number(x.budget_weight||0)}</strong><p>${esc(x.selection_reason)}</p><small>比較判断：${esc(x.decision_reason)}</small>${(x.conflicts||[]).length?`<small>反対材料：${esc(x.conflicts.join(" / "))}</small>`:""}${(x.risks||[]).length?`<small>リスク：${esc(x.risks.join(" / "))}</small>`:""}</div>`).join("")}`}if(a.race_id||a.action){return `<article class="ai-prediction"><div><b>${a.action==="BET"?"AIが購入":"AIが見送り"}</b><span>信頼度 ${esc(a.overall_confidence||"—")}</span></div><p>${esc(a.reason)}</p><div class="rollover-plan"><b>独立指数の扱い</b><span>${esc(a.independent_basis||"記録なし")}</span></div><div class="rollover-plan"><b>外部評価の扱い</b><span>${esc(a.external_consensus_assessment||"記録なし")}</span></div><div class="rollover-plan"><b>予算判断</b><span>${esc(a.budget_reason||"記録なし")}</span></div>${(a.contradicting_evidence||[]).map(x=>`<small class="caveat">反対材料：${esc(x)}</small>`).join("")}${(a.data_caveats||[]).map(x=>`<small class="caveat">注意点：${esc(x)}</small>`).join("")}${(a.bets||[]).map(b=>`<div class="ai-bet"><b>${b.decision==="BUY"?"購入":"見送り"}・${betLabels[b.bet_type]||b.bet_type} ${(b.horses||[]).join("-")}</b><span>${b.decision==="BUY"?yen(b.stake):"0円"} / 的中推定 ${pct(Number(b.hit_probability||0)*100)}</span><p>${esc(b.reason)}</p><small>オッズ評価：${esc(b.odds_assessment)}</small><small>金額理由：${esc(b.stake_reason)}</small><small>最大リスク：${esc(b.risk)}</small></div>`).join("")}</article>`}const list=a.predictions||[];return list.length?list.map(x=>renderAnswer(x,preds)).join(""):`<details><summary>GeminiのJSON回答</summary><pre>${esc(JSON.stringify(a,null,2))}</pre></details>`}
function decisionCard(d){const ok=d.decision!=="rejected",aiRejected=d.reason_code==="AI_REJECTED",label=ok?"AI購入":aiRejected?"AI見送り":"購入条件エラー",odds=Number(d.odds),ev=Number(d.expected_value);return `<article class="decision ${d.decision}"><div class="decision-state">${ok?"✓":aiRejected?"—":"×"}<span>${label}</span></div><div><b>${betLabels[d.bet_type]||d.bet_type} ${(d.combination||[]).join("-")}</b><p>${esc(d.reason_detail||"購入条件を確認しました")}</p><div class="checks"><span>AI決定額 <b>${yen(d.proposed_stake)}</b></span><span>保存額 <b>${yen(d.final_stake)}</b></span>${Number.isFinite(odds)?`<span>最低オッズ <b>${odds.toFixed(1)}倍</b></span>`:""}${Number.isFinite(ev)?`<span>監査EV <b>${ev.toFixed(2)}</b></span>`:""}<span>システム確認 <b>形式・残高・オッズ・ガミ防止</b></span></div></div></article>`}
function renderOperations(){const pipeline=pipelineItems.slice(0,40).map(x=>`<div class="audit-row"><b>${x.races?`${new Date(x.races.start_time).toLocaleDateString("ja-JP",{month:"numeric",day:"numeric"})} ${esc(x.races.track)} ${x.races.race_number}R`:dt(x.updated_at)}</b><span>${stateLabels[x.state]||esc(x.state)}<small>${x.races?esc(x.races.race_name):""}${x.selection_reason?` / ${esc(x.selection_reason)}`:""}${x.last_error?` / ${esc(x.last_error)}`:""}</small></span><em class="status ${x.state==="failed"||x.state==="invalid_output"?"failed":x.state==="completed"||x.state==="final_decided"?"succeeded":""}">${stateLabels[x.state]||x.state}</em></div>`).join("");const history=batches.map(b=>`<div class="audit-row"><b>${dt(b.started_at)}</b><span>${esc(b.parser_version)}<small>${b.races_fetched}レース / API ${b.api_requests}回${b.error_message?` / ${esc(b.error_message)}`:""}</small></span><em class="status ${b.status}">${b.status}</em></div>`).join("");$("#audit-list").innerHTML=pipeline||history||empty("履歴はありません")}
function empty(s){return `<div class="empty-state"><span>${esc(s)}</span></div>`}function showError(s){$("#error").hidden=false;$("#error").textContent=s}function logout(){localStorage.removeItem("race-lab-session");session=null;$("#auth").classList.remove("hidden")}
document.addEventListener("click",e=>{const page=e.target.closest("[data-page]"),strategy=e.target.closest("[data-strategy]"),card=e.target.closest("[data-open-strategy]"),call=e.target.closest("[data-ai-call],[data-open-call]"),raceTarget=e.target.closest("[data-scroll-race]"),pageTarget=e.target.closest("[data-page-target]"),refreshNow=e.target.closest("[data-refresh-now]"),pushToggle=e.target.closest("[data-push-toggle]");if(page){document.querySelectorAll("[data-page],.page").forEach(x=>x.classList.remove("active"));page.classList.add("active");$(`#${page.dataset.page}`).classList.add("active");$("#page-title").textContent=page.textContent.trim()}if(strategy){activeStrategy=strategy.dataset.strategy;renderToday()}if(card){activeStrategy=card.dataset.openStrategy;document.querySelector('[data-page="today"]').click()}if(call){document.querySelector('[data-page="trace"]').click();openCall(call.dataset.aiCall||call.dataset.openCall)}if(raceTarget){const target=document.querySelector(`[data-timeline-race="${CSS.escape(raceTarget.dataset.scrollRace)}"]`);target?.scrollIntoView({behavior:"smooth",block:"center"});target?.classList.add("focus-pulse");setTimeout(()=>target?.classList.remove("focus-pulse"),1600)}if(pageTarget)document.querySelector(`[data-page="${pageTarget.dataset.pageTarget}"]`)?.click();if(refreshNow)load();if(pushToggle)togglePush()});
let installPrompt=null;window.addEventListener("beforeinstallprompt",event=>{event.preventDefault();installPrompt=event;$("#pwa-install").hidden=false});$("#pwa-install").addEventListener("click",async()=>{if(!installPrompt)return;await installPrompt.prompt();installPrompt=null;$("#pwa-install").hidden=true});window.addEventListener("appinstalled",()=>{$("#pwa-install").hidden=true;installPrompt=null});
if("serviceWorker" in navigator){window.addEventListener("load",async()=>{try{const registration=await navigator.serviceWorker.register("./sw.js");const showUpdate=worker=>{if(!worker)return;const toast=$("#pwa-update");toast.hidden=false;toast.querySelector("button").onclick=()=>worker.postMessage({type:"SKIP_WAITING"})};if(registration.waiting)showUpdate(registration.waiting);registration.addEventListener("updatefound",()=>{const worker=registration.installing;worker?.addEventListener("statechange",()=>{if(worker.state==="installed"&&navigator.serviceWorker.controller)showUpdate(worker)})});let refreshing=false;navigator.serviceWorker.addEventListener("controllerchange",()=>{if(refreshing)return;refreshing=true;location.reload()})}catch(error){console.warn("PWA registration failed",error)}})}
setInterval(()=>{if(session&&pipelineItems.length)renderDashboard()},30000);setInterval(()=>{if(session&&!document.hidden)load()},180000);
[$("#trace-purpose"),$("#trace-strategy")].forEach(x=>x.addEventListener("change",renderCalls));$("#logout").addEventListener("click",logout);$("#auth-form").addEventListener("submit",async e=>{e.preventDefault();try{$("#auth-message").textContent="ログイン中…";session=await auth("token?grant_type=password",{email:$("#email").value,password:$("#password").value});localStorage.setItem("race-lab-session",JSON.stringify(session));$("#auth").classList.add("hidden");$("#auth-message").textContent="";load()}catch(x){$("#auth-message").textContent=x.message}});$("#signup").addEventListener("click",async()=>{try{$("#auth-message").textContent="作成中…";const d=await auth("signup",{email:$("#email").value,password:$("#password").value,data:{display_name:$("#email").value.split("@")[0]}});$("#auth-message").textContent=d.access_token?"作成しました":"確認メールを送信しました"}catch(x){$("#auth-message").textContent=x.message}});$("#today-label").textContent=new Date().toLocaleDateString("ja-JP",{year:"numeric",month:"long",day:"numeric",weekday:"long"});if(session){$("#auth").classList.add("hidden");load()}
