const SUPABASE_URL="https://lgpvvwymvqzhoqkpuyjv.supabase.co",SUPABASE_KEY="sb_publishable_OFguESiAuWQ8iHFzYgT-Mg_g-iL9-87",AUDIT_LOG_START="2026-08-08T12:42:30.541Z";
const labels={single:"単一AI"},betLabels={win:"単勝",place:"複勝",wide:"ワイド",quinella:"馬連",exacta:"馬単",trio:"3連複",trifecta:"3連単"};
let session=JSON.parse(localStorage.getItem("race-lab-session")||"null"),accounts=[],predictions=[],batches=[],allBets=[],selections=[],aiCalls=[],activeStrategy="single",selectedCall=null;
const $=s=>document.querySelector(s),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),yen=n=>`${Number(n||0)<0?"-":""}¥${Math.abs(Number(n||0)).toLocaleString()}`,pct=n=>`${Number(n||0).toFixed(1)}%`,dt=v=>new Date(v).toLocaleString("ja-JP"),jst=v=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo"}).format(new Date(v));
async function auth(path,body){const r=await fetch(`${SUPABASE_URL}/auth/v1/${path}`,{method:"POST",headers:{apikey:SUPABASE_KEY,"content-type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.msg||d.error_description||d.message||"認証に失敗しました");return d}
async function api(table,q=""){const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}?${q}`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${session.access_token}`}}),d=await r.json();if(r.status===401){logout();throw new Error("ログイン期限が切れました")}if(!r.ok)throw new Error(d.message||"データ取得に失敗しました");return d}
async function load(){try{[accounts,predictions,batches,allBets,selections,aiCalls]=await Promise.all([
 api("strategy_accounts","select=*&order=strategy"),
 api("predictions",`predicted_at=gte.${AUDIT_LOG_START}&select=id,ai_call_id,strategy,action,confidence,reason,predicted_at,raw_response,races(id,track,race_number,race_name,start_time,surface,distance,condition,status),bets(id,bet_type,combination,stake,odds_at_prediction,raw_estimated_probability,estimated_probability,expected_value,reason,stake_reason,settlements(return_amount,profit,is_hit)),bet_decisions(*)&order=predicted_at.desc&limit=100`),
 api("batch_runs","select=*&order=started_at.desc&limit=30"),api("bets","select=strategy,stake,estimated_probability,settlements(return_amount,profit,is_hit)&limit=5000"),
 api("race_selections","select=race_id,strategy,reason,rank,ai_call_id,created_at&order=created_at.desc&limit=500"),
 api("ai_calls",`strategy=eq.single&requested_at=gte.${AUDIT_LOG_START}&select=id,batch_run_id,purpose,strategy,provider,model,prompt_version,input_hash,output_hash,input_tokens,output_tokens,status,requested_at,completed_at,error_message&order=requested_at.desc&limit=100`)]);render()}catch(e){showError(e.message)}}
function render(){renderOverview();renderToday();renderAnalytics();renderCalls();renderOperations()}
function renderOverview(){const total=accounts.reduce((n,a)=>n+Number(a.current_balance)-Number(a.initial_balance),0);$("#total-profit").textContent=`${total>=0?"+":""}${yen(total)}`;$("#strategy-cards").innerHTML=accounts.map(a=>{const p=Number(a.current_balance)-Number(a.initial_balance),roi=a.total_staked?Number(a.total_returned)/Number(a.total_staked)*100:0;return `<article class="card strategy-link" data-open-strategy="${a.strategy}"><div class="card-top"><span class="badge ${a.strategy}">${labels[a.strategy]}</span><span>予想・履歴を見る →</span></div><small>現在残高</small><strong>${yen(a.current_balance)}</strong><div class="stats"><div><small>累計損益</small><b class="${p>=0?"positive":"negative"}">${p>=0?"+":""}${yen(p)}</b></div><div><small>回収率</small><b>${pct(roi)}</b></div><div><small>最低残高</small><b>${yen(a.minimum_balance)}</b></div></div></article>`}).join("");const max=Math.max(...accounts.map(a=>Number(a.current_balance)),1);$("#balance-bars").innerHTML=accounts.map(a=>`<div class="balance-row"><span>${labels[a.strategy]}</span><i><b class="${a.strategy}" style="width:${Math.max(3,Number(a.current_balance)/max*100)}%"></b></i><strong>${yen(a.current_balance)}</strong></div>`).join("");const latest=batches[0];$("#last-run").textContent=latest?`最終実行 ${dt(latest.started_at)}`:"実行履歴なし";$("#job-list").innerHTML=batches.slice(0,4).map(b=>`<div class="job"><i>${b.status==="succeeded"?"✓":"•"}</i><div><b>${b.target_date} / ${esc(b.parser_version)}</b><small>${b.races_fetched}レース・API ${b.api_requests}回</small></div><em class="status ${b.status}">${b.status}</em></div>`).join("")||empty("実行履歴はありません")}
function renderToday(){const ids=Object.keys(labels);$("#strategy-tabs").innerHTML=ids.map(x=>`<button class="${x===activeStrategy?"active":""}" data-strategy="${x}">${labels[x]}</button>`).join("");const list=predictions.filter(p=>p.strategy===activeStrategy),today=jst(new Date()),now=list.filter(p=>jst(p.races.start_time)===today),past=list.filter(p=>jst(p.races.start_time)!==today);$("#race-list").innerHTML=group("本日の予想",now,"本日の予想はまだありません")+group("過去の履歴",past,"過去の履歴はありません")}
function group(title,items,msg){return `<section class="race-group"><div class="race-group-title"><h2>${title}</h2><span>${items.length}レース</span></div>${items.length?items.map(raceCard).join(""):empty(msg)}</section>`}
function raceCard(p){const r=p.races,bets=p.bets||[],decisions=p.bet_decisions||[],stake=bets.reduce((n,b)=>n+Number(b.stake),0),returned=bets.reduce((n,b)=>n+Number((b.settlements?.[0]||{}).return_amount||0),0);return `<article class="race"><div class="race-heading"><div><small>${new Date(r.start_time).toLocaleDateString("ja-JP")}・${r.surface==="turf"?"芝":"ダート"} ${r.distance||"—"}m</small><div><strong>${esc(r.track)} ${r.race_number}R</strong><span>${esc(r.race_name)}</span></div></div><span class="outcome ${p.action}">${p.action==="bet"?bets.length?"購入":"見送り":"見送り"}</span></div><p class="race-copy">${esc(p.reason)}</p>${bets.map(b=>`<div class="bet"><b>${betLabels[b.bet_type]||b.bet_type} ${b.combination.join("-")}</b><span>${yen(b.stake)}</span><small>オッズ ${Number(b.odds_at_prediction).toFixed(1)} / EV ${Number(b.expected_value).toFixed(2)}</small></div>`).join("")}<div class="decision-link" data-open-call="${p.ai_call_id}">AI入力と判断根拠を見る <b>→</b></div><div class="race-result"><span>購入 ${yen(stake)}</span><span>払戻 ${r.status==="finished"?yen(returned):"—"}</span><span>判定ログ ${decisions.length}件</span></div></article>`}
function renderAnalytics(){const stats=accounts.map(a=>({...a,...RaceAnalytics.strategyStats(allBets,a.strategy)})),tot=RaceAnalytics.validationStats(allBets);$("#analysis-metrics").innerHTML=[["検証済み馬券",tot.count],["確率誤差",pct(tot.calibrationGap*100)],["Brierスコア",tot.brierScore.toFixed(3)],["AI処理履歴",aiCalls.length]].map(x=>`<div class="metric"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join("");$("#analysis-table").innerHTML=stats.map(a=>`<tr><td><span class="badge ${a.strategy}">${labels[a.strategy]}</span></td><td>${yen(a.staked)}</td><td>${yen(a.returned)}</td><td class="${a.profit>=0?"positive":"negative"}">${yen(a.profit)}</td><td>${pct(a.roi)}</td><td>${pct(a.predictedRate*100)}</td><td>${pct(a.observedRate*100)}</td><td>${pct(a.calibrationGap*100)}</td><td>${a.brierScore.toFixed(3)}</td></tr>`).join("")}
function filteredCalls(){const purpose=$("#trace-purpose").value,strategy=$("#trace-strategy").value;return aiCalls.filter(c=>(purpose==="all"||c.purpose===purpose)&&(strategy==="all"||c.strategy===strategy))}
function renderCalls(){const rows=filteredCalls(),names={screening:"分析",prediction:"買い目提案",audit:"最終判断"};$("#call-list").innerHTML=rows.map(c=>`<button class="call-item ${selectedCall===c.id?"active":""}" data-ai-call="${c.id}"><span><b>${names[c.purpose]||c.purpose}</b><em class="status ${c.status}">${c.status}</em></span><strong>${c.strategy?labels[c.strategy]:"単一AI"}</strong><small>${dt(c.requested_at)}・${esc(c.model)}</small><small>入力 ${Number(c.input_tokens||0).toLocaleString()} / 出力 ${Number(c.output_tokens||0).toLocaleString()} tokens</small></button>`).join("")||empty("条件に一致するAI処理はありません")}
function modelAnswer(response){const text=response?.candidates?.[0]?.content?.parts?.map(p=>p.text).filter(Boolean).join("\n");if(!text)return null;try{return JSON.parse(text)}catch{return text}}
function promptPayload(prompt){const value=String(prompt||"");for(let i=value.length-1;i>=0;i--){if(value[i]!=="["&&value[i]!=="{")continue;try{const parsed=JSON.parse(value.slice(i));if(Array.isArray(parsed))return parsed}catch{}}return []}
function inputView(call){const rows=promptPayload(call.request_json?.prompt);if(!rows.length)return `<div class="legacy-note">入力データを読み取れませんでした。</div>`;if(call.purpose==="screening")return `<div class="input-summary"><span><b>${rows.length}</b>件を分析</span><span><b>1</b>単一AI</span></div><div class="data-grid">${rows.map(r=>`<article class="data-card"><b>${esc(r.track||"分析結果")} ${r.race_number||r.raceNumber||""}R</b><strong>${esc(r.race_name||r.raceName||r.race_id||"")}</strong><small>${r.surface==="turf"?"芝":r.surface==="dirt"?"ダート":esc(r.surface||"")} ${r.distance?`・${r.distance}m`:""}</small></article>`).join("")}</div>`;return rows.map(r=>raceInputCard(r)).join("")}
function raceInputCard(row){const race=row.race||{},entries=row.entries||[],evals=row.evaluations||[],odds=row.odds||[],byNumber=new Map(entries.map(e=>[e.horseNumber,e]));return `<article class="input-race"><div class="input-race-head"><div><b>${esc(race.track)} ${race.raceNumber||race.race_number||""}R</b><strong>${esc(race.raceName||race.race_name||"")}</strong></div><span>${race.surface==="turf"?"芝":race.surface==="dirt"?"ダート":esc(race.surface||"—")} ${race.distance||"—"}m</span></div><h4>出走馬の総合評価</h4><div class="table-wrap compact"><table><thead><tr><th>馬</th><th>総合</th><th>能力</th><th>適性</th><th>状態</th><th>展開</th><th>推定勝率</th><th>品質</th><th>人気/単勝</th></tr></thead><tbody>${evals.sort((a,b)=>b.overallScore-a.overallScore).map(e=>{const entry=byNumber.get(e.horseNumber)||{};return `<tr><td><b>${e.horseNumber} ${esc(e.horseName||entry.horseName)}</b><small>${esc(entry.jockey||"")}</small></td><td><strong>${Number(e.overallScore).toFixed(1)}</strong></td><td>${Number(e.abilityScore).toFixed(1)}</td><td>${Number(e.suitabilityScore).toFixed(1)}</td><td>${Number(e.conditionScore).toFixed(1)}</td><td>${Number(e.raceContextScore).toFixed(1)}</td><td>${pct(Number(e.estimatedWinProbability)*100)}</td><td>${pct(Number(e.dataQuality)*100)}<small>${e.sampleSize}走</small></td><td>${entry.popularity||"—"}人気 / ${entry.winOdds||"—"}</td></tr>`}).join("")}</tbody></table></div><details><summary>AIが比較したオッズ ${odds.length}件</summary><div class="odds-grid">${odds.map(o=>`<span><b>${betLabels[o.type]||o.type} ${(o.horses||[]).join("-")}</b>${Number(o.odds).toFixed(1)}倍${o.popularity?`・${o.popularity}人気`:""}</span>`).join("")}</div></details></article>`}
async function openCall(id){selectedCall=id;renderCalls();const el=$("#trace-detail");el.innerHTML='<div class="loading">監査データを読み込んでいます…</div>';try{const [callRows,preds]=await Promise.all([api("ai_calls",`id=eq.${encodeURIComponent(id)}&select=*`),api("predictions",`ai_call_id=eq.${encodeURIComponent(id)}&select=id,strategy,action,confidence,reason,raw_response,races(track,race_number,race_name,start_time),bets(*),bet_decisions(*)&order=predicted_at`)]),call=callRows[0];if(!call)throw new Error("AI処理が見つかりません");renderTrace(call,preds)}catch(e){el.innerHTML=empty(e.message)}}
function renderTrace(call,preds){const answer=modelAnswer(call.response_json),decisions=preds.flatMap(p=>(p.bet_decisions||[]).map(d=>({...d,race:p.races,prediction:p}))),purchased=decisions.filter(d=>d.decision!=="rejected").length,rejected=decisions.filter(d=>d.decision==="rejected").length;$("#trace-detail").innerHTML=`<div class="trace-title"><div><span class="badge ${call.strategy||"screening"}">${call.strategy?labels[call.strategy]:"全戦略"}</span><h2>${call.purpose==="prediction"?"予測AI":"レース選定AI"}</h2><p>${dt(call.requested_at)}・${esc(call.provider)} / ${esc(call.model)}</p></div><div class="trace-summary"><b>${purchased}</b><small>購入</small><b>${rejected}</b><small>見送り</small></div></div>
<section class="trace-step"><div class="step-no">1</div><div><p class="eyebrow">AI INPUT</p><h3>AIに渡したデータ</h3><p>対象レース、出走馬の評価、予測確率、データ品質、オッズを読みやすく整理しています。</p><div class="hashes"><span>対象データ改ざん検知済み</span><span>${Number(call.input_tokens||0).toLocaleString()} tokens</span></div>${inputView(call)}</div></section>
<section class="trace-step"><div class="step-no">2</div><div><p class="eyebrow">AI RESPONSE</p><h3>AIの回答</h3>${renderAnswer(answer,preds)}</div></section>
<section class="trace-step"><div class="step-no">3</div><div><p class="eyebrow">PROGRAM DECISION</p><h3>プログラムの判定</h3>${decisions.length?decisions.map(decisionCard).join(""):`<div class="legacy-note">${call.purpose==="screening"?"この処理はレース候補の選定です。購入判定は後続の予測AIで行います。":"AIは購入候補を提案しませんでした。"}</div>`}</div></section>
<section class="trace-step final"><div class="step-no">4</div><div><p class="eyebrow">FINAL RESULT</p><h3>最終結果</h3>${preds.length?preds.map(p=>`<div class="final-row"><b>${esc(p.races.track)} ${p.races.race_number}R ${esc(p.races.race_name)}</b><span>${p.action==="bet"&&(p.bets||[]).length?`${p.bets.length}点・${yen(p.bets.reduce((n,b)=>n+Number(b.stake),0))}`:"見送り"}</span></div>`).join(""):"後続の予測処理で購入を決定します。"}</div></section>`}
function renderAnswer(a,preds){if(!a)return `<div class="legacy-note">AIから有効な回答を取得できませんでした。</div>`;if(typeof a==="string")return `<div class="legacy-note">${esc(a)}</div>`;const list=a.predictions||[];if(list.length)return `<div class="answer-box"><div><small>回答レース</small><strong>${list.length}件</strong></div><div><small>保存された予測</small><strong>${preds.length}件</strong></div></div>${list.map(x=>`<article class="ai-prediction"><div><b>${x.action==="BET"?"購入候補":"見送り"}</b><span>信頼度 ${x.confidence||0}%</span></div><p>${esc(x.reason)}</p>${(x.bets||[]).map(b=>`<div class="ai-bet"><b>${betLabels[b.type]||b.type} ${(b.horses||[]).join("-")}</b><span>提案 ${yen(b.stake)}・AI確率 ${pct(Number(b.estimated_probability)*100)}</span><p>${esc(b.reason)}</p><small>金額根拠：${esc(b.stake_reason)}</small></div>`).join("")}</article>`).join("")}`;const groups=Object.keys(labels).flatMap(strategy=>(Array.isArray(a[strategy])?a[strategy]:[]).map(x=>({...x,strategy})));return `<div class="answer-box"><div><small>選定レース</small><strong>${groups.length}件</strong></div><div><small>後続処理</small><strong>戦略別予測へ</strong></div></div>${groups.map(x=>`<div class="selection-answer"><span class="badge ${x.strategy}">${labels[x.strategy]}</span><b>${esc(x.race_id)}</b><strong>評価 ${x.score??"—"}</strong><p>${esc(x.reason)}</p></div>`).join("")}`}
function decisionCard(d){const ok=d.decision!=="rejected";return `<article class="decision ${d.decision}"><div class="decision-state">${ok?"✓":"×"}<span>${d.decision==="purchased"?"購入":d.decision==="reduced"?"減額購入":"見送り"}</span></div><div><b>${betLabels[d.bet_type]||d.bet_type} ${(d.combination||[]).join("-")}</b><p>${esc(d.reason_detail)}</p><div class="checks"><span>データ品質 <b>${Number(d.data_quality||0).toFixed(2)}</b> / ${Number(d.minimum_data_quality).toFixed(2)}</span><span>AI確率 <b>${pct(Number(d.raw_probability)*100)}</b> → 補正 ${pct(Number(d.calibrated_probability)*100)}</span><span>期待値 <b>${d.expected_value==null?"—":Number(d.expected_value).toFixed(2)}</b> / ${Number(d.minimum_expected_value).toFixed(2)}</span><span>金額 <b>${yen(d.proposed_stake)}</b> → ${yen(d.final_stake)}</span></div></div></article>`}
function renderOperations(){$("#audit-list").innerHTML=batches.map(b=>`<div class="audit-row"><b>${dt(b.started_at)}</b><span>${esc(b.parser_version)}<small>${b.races_fetched}レース / API ${b.api_requests}回${b.error_message?` / ${esc(b.error_message)}`:""}</small></span><em class="status ${b.status}">${b.status}</em></div>`).join("")||empty("履歴はありません")}
function empty(s){return `<div class="empty-state"><span>${esc(s)}</span></div>`}function showError(s){$("#error").hidden=false;$("#error").textContent=s}function logout(){localStorage.removeItem("race-lab-session");session=null;$("#auth").classList.remove("hidden")}
document.addEventListener("click",e=>{const page=e.target.closest("[data-page]"),strategy=e.target.closest("[data-strategy]"),card=e.target.closest("[data-open-strategy]"),call=e.target.closest("[data-ai-call],[data-open-call]");if(page){document.querySelectorAll("[data-page],.page").forEach(x=>x.classList.remove("active"));page.classList.add("active");$(`#${page.dataset.page}`).classList.add("active");$("#page-title").textContent=page.textContent.trim()}if(strategy){activeStrategy=strategy.dataset.strategy;renderToday()}if(card){activeStrategy=card.dataset.openStrategy;document.querySelector('[data-page="today"]').click()}if(call){document.querySelector('[data-page="trace"]').click();openCall(call.dataset.aiCall||call.dataset.openCall)}});
let installPrompt=null;window.addEventListener("beforeinstallprompt",event=>{event.preventDefault();installPrompt=event;$("#pwa-install").hidden=false});$("#pwa-install").addEventListener("click",async()=>{if(!installPrompt)return;await installPrompt.prompt();installPrompt=null;$("#pwa-install").hidden=true});window.addEventListener("appinstalled",()=>{$("#pwa-install").hidden=true;installPrompt=null});
if("serviceWorker" in navigator){window.addEventListener("load",async()=>{try{const registration=await navigator.serviceWorker.register("./sw.js");const showUpdate=worker=>{if(!worker)return;const toast=$("#pwa-update");toast.hidden=false;toast.querySelector("button").onclick=()=>worker.postMessage({type:"SKIP_WAITING"})};if(registration.waiting)showUpdate(registration.waiting);registration.addEventListener("updatefound",()=>{const worker=registration.installing;worker?.addEventListener("statechange",()=>{if(worker.state==="installed"&&navigator.serviceWorker.controller)showUpdate(worker)})});let refreshing=false;navigator.serviceWorker.addEventListener("controllerchange",()=>{if(refreshing)return;refreshing=true;location.reload()})}catch(error){console.warn("PWA registration failed",error)}})}
[$("#trace-purpose"),$("#trace-strategy")].forEach(x=>x.addEventListener("change",renderCalls));$("#logout").addEventListener("click",logout);$("#auth-form").addEventListener("submit",async e=>{e.preventDefault();try{$("#auth-message").textContent="ログイン中…";session=await auth("token?grant_type=password",{email:$("#email").value,password:$("#password").value});localStorage.setItem("race-lab-session",JSON.stringify(session));$("#auth").classList.add("hidden");$("#auth-message").textContent="";load()}catch(x){$("#auth-message").textContent=x.message}});$("#signup").addEventListener("click",async()=>{try{$("#auth-message").textContent="作成中…";const d=await auth("signup",{email:$("#email").value,password:$("#password").value,data:{display_name:$("#email").value.split("@")[0]}});$("#auth-message").textContent=d.access_token?"作成しました":"確認メールを送信しました"}catch(x){$("#auth-message").textContent=x.message}});$("#today-label").textContent=new Date().toLocaleDateString("ja-JP",{year:"numeric",month:"long",day:"numeric",weekday:"long"});if(session){$("#auth").classList.add("hidden");load()}
