const SUPABASE_URL="https://lgpvvwymvqzhoqkpuyjv.supabase.co",SUPABASE_KEY="sb_publishable_OFguESiAuWQ8iHFzYgT-Mg_g-iL9-87",AUDIT_LOG_START="2026-08-08T12:42:30.541Z";
const labels={single:"Gemini AI"},betLabels={win:"単勝",place:"複勝",wide:"ワイド"};
const stateLabels={stage1_pending:"一次判定待ち",stage1_rejected:"一次除外",evidence_pending:"外部情報取得中",evidence_ready:"情報準備完了",evidence_insufficient:"情報不足",selected:"Gemini選定",not_selected:"非選定",final_refresh_pending:"直前更新待ち",final_decided:"最終判断済み",invalid_output:"AI出力訂正中",completed:"完了",failed:"エラー"};
let session=JSON.parse(localStorage.getItem("race-lab-session")||"null"),accounts=[],predictions=[],batches=[],allBets=[],selections=[],aiCalls=[],pipelineItems=[],rollovers=[],reservations=[],sourceSnapshots=[],activeStrategy="single",selectedCall=null;
const $=s=>document.querySelector(s),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),yen=n=>`${Number(n||0)<0?"-":""}¥${Math.abs(Number(n||0)).toLocaleString()}`,pct=n=>`${Number(n||0).toFixed(1)}%`,dt=v=>new Date(v).toLocaleString("ja-JP"),jst=v=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo"}).format(new Date(v));
async function auth(path,body){const r=await fetch(`${SUPABASE_URL}/auth/v1/${path}`,{method:"POST",headers:{apikey:SUPABASE_KEY,"content-type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.msg||d.error_description||d.message||"認証に失敗しました");return d}
async function api(table,q=""){const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}?${q}`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${session.access_token}`}}),d=await r.json();if(r.status===401){logout();throw new Error("ログイン期限が切れました")}if(!r.ok)throw new Error(d.message||"データ取得に失敗しました");return d}
async function optionalApi(table,q=""){try{return await api(table,q)}catch(error){console.warn(`${table}: ${error.message}`);return []}}
async function load(){try{$("#error").hidden=true;$("#refresh-data").disabled=true;[accounts,predictions,batches,allBets,selections,aiCalls,pipelineItems,rollovers,reservations,sourceSnapshots]=await Promise.all([
 api("strategy_accounts","select=*&order=strategy"),
 api("predictions",`predicted_at=gte.${AUDIT_LOG_START}&select=id,ai_call_id,strategy,action,confidence,reason,predicted_at,raw_response,races(id,track,race_number,race_name,start_time,surface,distance,condition,status,race_results(finish_order,confirmed_at)),bets(id,bet_type,combination,stake,odds_at_prediction,raw_estimated_probability,estimated_probability,expected_value,reason,stake_reason,settlements(return_amount,profit,is_hit,settled_at)),bet_decisions(*)&order=predicted_at.desc&limit=100`),
 api("batch_runs","select=*&order=started_at.desc&limit=30"),api("bets","select=strategy,stake,estimated_probability,settlements(return_amount,profit,is_hit)&limit=5000"),
 api("race_selections","select=race_id,strategy,reason,rank,ai_call_id,created_at&order=created_at.desc&limit=500"),
 api("ai_calls",`strategy=eq.single&requested_at=gte.${AUDIT_LOG_START}&select=id,batch_run_id,purpose,strategy,provider,model,prompt_version,input_hash,output_hash,input_tokens,output_tokens,status,requested_at,completed_at,error_message&order=requested_at.desc&limit=100`),
 optionalApi("race_pipeline_items","select=id,batch_run_id,state,evidence_quality,selection_rank,selection_reason,next_action_at,last_error,updated_at,races(id,track,race_number,race_name,start_time,status)&order=updated_at.desc&limit=200"),
 optionalApi("rollover_states","select=*&order=strategy"),
 optionalApi("paper_fund_reservations","select=strategy,amount,status,reserved_at&order=reserved_at.desc&limit=100"),
 optionalApi("source_data_snapshots","select=race_id,stage,source_name,identity_status,captured_at&order=captured_at.desc&limit=200")]);render()}catch(e){showError(e.message)}finally{$("#refresh-data").disabled=false}}
function render(){renderOverview();renderDashboard();renderToday();renderAnalytics();renderCalls();renderOperations()}
function renderOverview(){
 const total=accounts.reduce((n,a)=>n+Number(a.current_balance)-Number(a.initial_balance),0),openReserved=reservations.filter(r=>r.status==="open").reduce((n,r)=>n+Number(r.amount),0),rollover=rollovers.find(r=>r.strategy==="single");
 $("#total-profit").textContent=`${total>=0?"+":""}${yen(total)}`;
 $("#strategy-cards").innerHTML=accounts.map(a=>{const p=Number(a.current_balance)-Number(a.initial_balance),roi=a.total_staked?Number(a.total_returned)/Number(a.total_staked)*100:0,available=Math.max(0,Number(a.current_balance)-openReserved);return `<article class="card strategy-link" data-open-strategy="${a.strategy}"><div class="card-top"><span class="badge ${a.strategy}">${labels[a.strategy]}</span><span>予想・履歴を見る →</span></div><small>利用可能なペーパー資金</small><strong>${yen(available)}</strong><div class="stats"><div><small>現在残高</small><b>${yen(a.current_balance)}</b></div><div><small>予約中</small><b>${yen(openReserved)}</b></div><div><small>回収率</small><b>${pct(roi)}</b></div></div></article>`}).join("");
 const max=Math.max(...accounts.map(a=>Number(a.current_balance)),1);$("#balance-bars").innerHTML=accounts.map(a=>`<div class="balance-row"><span>${labels[a.strategy]}</span><i><b class="${a.strategy}" style="width:${Math.max(3,Number(a.current_balance)/max*100)}%"></b></i><strong>${yen(a.current_balance)}</strong></div>`).join("")+`<div class="rollover-row"><span>複勝ころがし</span><strong>${yen(rollover?.pending_amount||0)}</strong><small>${Number(rollover?.consecutive_hits||0)}連続的中</small></div>`;
 renderPipelineSummary();
 const latest=batches[0];$("#last-run").textContent=latest?`最終実行 ${dt(latest.started_at)}`:"実行履歴なし";$("#job-list").innerHTML=batches.slice(0,4).map(b=>`<div class="job"><i>${b.status==="succeeded"?"✓":"•"}</i><div><b>${b.target_date} / ${esc(b.parser_version)}</b><small>${b.races_fetched}レース・API ${b.api_requests}回</small></div><em class="status ${b.status}">${b.status}</em></div>`).join("")||empty("実行履歴はありません")
}
function renderPipelineSummary(){
 const latestBatch=batches[0],items=latestBatch?pipelineItems.filter(x=>!x.races?.start_time||jst(x.races.start_time)===latestBatch.target_date):pipelineItems;
 const count=states=>items.filter(x=>states.includes(x.state)).length,sources=[...new Set(sourceSnapshots.map(x=>x.source_name))],failed=items.filter(x=>x.state==="failed"||x.state==="invalid_output").length;
 const steps=[{name:"Stage 1通過",value:count(["evidence_pending","evidence_ready","evidence_insufficient","selected","not_selected","final_refresh_pending","final_decided","completed"])},{name:"外部情報準備",value:count(["evidence_ready","selected","not_selected","final_refresh_pending","final_decided","completed"])},{name:"Gemini選定",value:count(["selected","final_refresh_pending","final_decided","completed"])},{name:"最終判断",value:count(["final_decided","completed"])}];
 $("#pipeline-summary").innerHTML=`<article class="panel pipeline-panel"><div class="panel-title"><h2>最新の予測フロー</h2><span>${failed?`要確認 ${failed}件`:"正常"}</span></div><div class="pipeline-steps">${steps.map((s,i)=>`<div><small>0${i+1}</small><b>${s.name}</b><strong>${s.value}</strong><span>レース</span></div>`).join("")}</div><div class="source-strip"><b>取得元</b>${sources.length?sources.map(s=>`<span>${esc(s)}</span>`).join(""):`<span>対象レースの情報待ち</span>`}</div></article>`;
}
const activeStates=["stage1_pending","evidence_pending","evidence_ready","selected","final_refresh_pending","invalid_output"];
function clock(v){return new Date(v).toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"})}
function countdown(v){const ms=Date.parse(v)-Date.now();if(ms<=0)return "まもなく";const mins=Math.ceil(ms/60000);return mins<60?`あと${mins}分`:`あと${Math.floor(mins/60)}時間${String(mins%60).padStart(2,"0")}分`}
function renderDashboard(){
 const today=jst(new Date()),todayItems=pipelineItems.filter(x=>x.races?.start_time&&jst(x.races.start_time)===today),todayPreds=predictions.filter(p=>p.races?.start_time&&jst(p.races.start_time)===today),purchased=todayPreds.filter(p=>p.action==="bet"&&(p.bets||[]).length),latest=batches[0];
 const active=todayItems.filter(x=>activeStates.includes(x.state)),failed=todayItems.filter(x=>x.state==="failed"||x.state==="invalid_output"),done=todayItems.filter(x=>["stage1_rejected","not_selected","final_decided","completed"].includes(x.state)).length,total=todayItems.length,progress=total?Math.round(done/total*100):0;
 const scheduled=todayItems.filter(x=>x.next_action_at&&Date.parse(x.next_action_at)>Date.now()).sort((a,b)=>Date.parse(a.next_action_at)-Date.parse(b.next_action_at)),next=scheduled[0];
 const phase=failed.length?{tone:"warning",icon:"!",label:"確認が必要です",copy:`${failed.length}件の処理を確認してください`}:active.some(x=>x.state==="evidence_pending")?{tone:"working",icon:"↻",label:"外部情報を収集中",copy:`${active.filter(x=>x.state==="evidence_pending").length}レースを順番に処理しています`}:active.some(x=>x.state==="selected")?{tone:"working",icon:"◎",label:"直前判断を待機中",copy:`選定済み${active.filter(x=>x.state==="selected").length}レース`}:latest?.status==="running"?{tone:"working",icon:"↻",label:"予測フローを実行中",copy:"次の処理を自動で開始します"}:total?{tone:"complete",icon:"✓",label:"本日の予測処理は完了",copy:`${total}レースを確認しました`}:{tone:"idle",icon:"○",label:"開催情報を待っています",copy:"開催日は07:00から自動で処理します"};
 $("#dashboard-command").innerHTML=`<section class="command-card ${phase.tone}"><div class="command-status"><span class="command-icon">${phase.icon}</span><div><p class="eyebrow">CURRENT STATUS</p><h2>${phase.label}</h2><p>${phase.copy}</p></div></div><div class="command-progress"><div><span>本日の進捗</span><strong>${progress}%</strong></div><i><b style="width:${progress}%"></b></i><small>${done} / ${total||0}レースが判定済み</small></div><div class="next-action"><small>次に起きること</small><strong>${next?`${clock(next.next_action_at)} ${esc(next.races.track)}${next.races.race_number}R 直前更新`:latest?.metadata?.selection_due_at?`${clock(latest.metadata.selection_due_at)} Gemini対象レース選定`:"次の予定はありません"}</strong><span>${next?countdown(next.next_action_at):"自動運転中"}</span></div></section>`;
 renderDashboardTimeline(todayItems,latest);
 $("#purchased-count").textContent=`${purchased.length}レース`;
 $("#dashboard-races").innerHTML=purchased.length?purchased.sort((a,b)=>Date.parse(a.races.start_time)-Date.parse(b.races.start_time)).map(dashboardRaceCard).join(""):empty("本日購入したレースはまだありません");
 $("#dashboard-next-races").innerHTML=`<article class="panel compact-panel"><div class="panel-title"><h2>これからの注目レース</h2><span>最終判断予定</span></div><div class="upcoming-list">${scheduled.length?scheduled.slice(0,5).map(x=>`<div class="upcoming-race"><time>${clock(x.next_action_at)}</time><div><b>${esc(x.races.track)} ${x.races.race_number}R</b><small>${esc(x.races.race_name)}・発走 ${clock(x.races.start_time)}</small></div><span>${countdown(x.next_action_at)}</span></div>`).join(""):empty("現在、判断予定のレースはありません")}</div></article>`;
 $("#dashboard-alerts").innerHTML=`<article class="panel compact-panel alert-panel ${failed.length?"has-alert":""}"><div class="panel-title"><h2>要確認</h2><span>${failed.length?`${failed.length}件`:"問題なし"}</span></div>${failed.length?failed.slice(0,3).map(x=>`<div class="alert-row"><b>${esc(x.races?.track||"")} ${x.races?.race_number||""}R</b><span>${stateLabels[x.state]||x.state}</span><small>${esc(x.last_error||"再処理を待っています")}</small></div>`).join(""):`<div class="all-clear"><span>✓</span><div><b>正常に稼働しています</b><small>エラーや情報不足はありません</small></div></div>`}</article>`;
 const stake=purchased.flatMap(p=>p.bets||[]).reduce((n,b)=>n+Number(b.stake),0),returned=purchased.flatMap(p=>p.bets||[]).reduce((n,b)=>n+Number(b.settlements?.[0]?.return_amount||0),0),settled=purchased.every(p=>(p.bets||[]).every(b=>b.settlements?.length));
 $("#dashboard-money").innerHTML=`<div class="money-grid"><div><small>投資</small><b>${yen(stake)}</b></div><div><small>払戻</small><b>${yen(returned)}</b></div><div class="money-profit"><small>${settled?"確定損益":"現在損益"}</small><strong class="${returned-stake>=0?"positive":"negative"}">${returned-stake>=0?"+":""}${yen(returned-stake)}</strong></div></div>`;
}
function renderDashboardTimeline(items,batch){
 const counts=s=>items.filter(x=>s.includes(x.state)).length,selectionDue=batch?.metadata?.selection_due_at;
 const steps=[
  {time:"07:00",label:"開催情報を取得",sub:items.length?`${items.length}レースを登録`:"開催確認",done:!!items.length},
  {time:"07:01",label:"一次判定",sub:items.length?`${counts(["stage1_rejected"])}除外・${items.length-counts(["stage1_pending","stage1_rejected"])}通過`:"待機中",done:items.length&&!counts(["stage1_pending"])},
  {time:selectionDue?clock(selectionDue):"09:00",label:"外部情報・Gemini選定",sub:counts(["evidence_pending"])?`${counts(["evidence_pending"])}レース処理待ち`:`${counts(["selected","not_selected","final_refresh_pending","final_decided","completed"])}レース判定`,active:counts(["evidence_pending","evidence_ready"])>0,done:items.length&&!counts(["stage1_pending","evidence_pending","evidence_ready"])},
  {time:"随時",label:"発走20分前の最終判断",sub:`${counts(["selected"])}予定・${counts(["final_decided","completed"])}完了`,active:counts(["selected","final_refresh_pending"])>0,done:items.length>0&&!counts(["selected","final_refresh_pending"])},
  {time:"発走後",label:"結果確認・自動精算",sub:"3分間隔で結果を確認",active:predictions.some(p=>p.races?.status==="running")}
 ];
 $("#dashboard-timeline").innerHTML=`<section class="dashboard-section timeline-section"><div class="section-heading"><div><p class="eyebrow">TODAY'S FLOW</p><h2>本日のタイムライン</h2></div><span class="live-pill"><i></i> 自動更新</span></div><div class="visual-timeline">${steps.map((s,i)=>`<div class="timeline-item ${s.done?"done":s.active?"active":"pending"}"><div class="timeline-marker">${s.done?"✓":s.active?"●":i+1}</div><time>${s.time}</time><div><b>${s.label}</b><small>${s.sub}</small></div><em>${s.done?"完了":s.active?"進行中":"予定"}</em></div>`).join("")}</div></section>`;
}
function dashboardRaceCard(p){
 const r=p.races,bets=p.bets||[],settled=bets.length&&bets.every(b=>b.settlements?.length),returned=bets.reduce((n,b)=>n+Number(b.settlements?.[0]?.return_amount||0),0),stake=bets.reduce((n,b)=>n+Number(b.stake),0),hit=settled&&bets.some(b=>b.settlements?.[0]?.is_hit),result=Array.isArray(r.race_results)?r.race_results[0]:r.race_results,state=settled?(hit?"hit":"miss"):Date.parse(r.start_time)<=Date.now()?"checking":"purchased",label=settled?(hit?"的中":"不的中"):state==="checking"?"結果確認中":"購入済み";
 return `<article class="dashboard-race ${state}"><div class="race-state"><span>${label}</span><time>${state==="purchased"?countdown(r.start_time):settled?`損益 ${returned-stake>=0?"+":""}${yen(returned-stake)}`:"3分間隔で確認"}</time></div><div class="dashboard-race-head"><div><small>${clock(r.start_time)} 発走</small><h3>${esc(r.track)} ${r.race_number}R</h3><p>${esc(r.race_name)}</p></div>${result?`<div class="finish-order"><small>確定着順</small><b>${result.finish_order.slice(0,3).join(" — ")}</b></div>`:""}</div><div class="ticket-list">${bets.map(b=>`<div><b>${betLabels[b.bet_type]||b.bet_type} ${(b.combination||[]).join("-")}</b><span>${yen(b.stake)}</span><em class="${b.settlements?.[0]?.is_hit?"positive":b.settlements?.length?"negative":""}">${b.settlements?.length?(b.settlements[0].is_hit?`払戻 ${yen(b.settlements[0].return_amount)}`:"外れ"):"結果待ち"}</em></div>`).join("")}</div><button class="race-log-link" data-open-call="${p.ai_call_id}">AIがこの判断をした理由 <b>→</b></button></article>`
}
function renderToday(){const ids=Object.keys(labels);$("#strategy-tabs").innerHTML=ids.map(x=>`<button class="${x===activeStrategy?"active":""}" data-strategy="${x}">${labels[x]}</button>`).join("");const list=predictions.filter(p=>p.strategy===activeStrategy),today=jst(new Date()),now=list.filter(p=>jst(p.races.start_time)===today),past=list.filter(p=>jst(p.races.start_time)!==today);$("#race-list").innerHTML=group("本日の予想",now,"本日の予想はまだありません")+group("過去の履歴",past,"過去の履歴はありません")}
function group(title,items,msg){return `<section class="race-group"><div class="race-group-title"><h2>${title}</h2><span>${items.length}レース</span></div>${items.length?items.map(raceCard).join(""):empty(msg)}</section>`}
function raceCard(p){const r=p.races,bets=p.bets||[],decisions=p.bet_decisions||[],stake=bets.reduce((n,b)=>n+Number(b.stake),0),returned=bets.reduce((n,b)=>n+Number((b.settlements?.[0]||{}).return_amount||0),0);return `<article class="race"><div class="race-heading"><div><small>${new Date(r.start_time).toLocaleDateString("ja-JP")}・${r.surface==="turf"?"芝":"ダート"} ${r.distance||"—"}m</small><div><strong>${esc(r.track)} ${r.race_number}R</strong><span>${esc(r.race_name)}</span></div></div><span class="outcome ${p.action}">${p.action==="bet"&&bets.length?"ペーパーBET":"AI見送り"}</span></div><div class="prediction-meta"><span>Gemini信頼度 ${Number(p.confidence||0)}%</span><span>T-20情報で判断</span></div><p class="race-copy">${esc(p.reason)}</p>${bets.map(b=>`<div class="bet"><b>${betLabels[b.bet_type]||b.bet_type} ${b.combination.join("-")}</b><span>${yen(b.stake)}</span><small>予測時オッズ ${Number(b.odds_at_prediction).toFixed(1)}${b.expected_value==null?"":` / 参考EV ${Number(b.expected_value).toFixed(2)}`}</small></div>`).join("")}<div class="decision-link" data-open-call="${p.ai_call_id}">Geminiへの入力と判断根拠を見る <b>→</b></div><div class="race-result"><span>投資 ${yen(stake)}</span><span>払戻 ${r.status==="finished"?yen(returned):"—"}</span><span>技術検証 ${decisions.length}件</span></div></article>`}
function renderAnalytics(){const stats=accounts.map(a=>({...a,...RaceAnalytics.strategyStats(allBets,a.strategy)})),tot=RaceAnalytics.validationStats(allBets);$("#analysis-metrics").innerHTML=[["検証済み馬券",tot.count],["確率誤差",pct(tot.calibrationGap*100)],["Brierスコア",tot.brierScore.toFixed(3)],["AI処理履歴",aiCalls.length]].map(x=>`<div class="metric"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join("");$("#analysis-table").innerHTML=stats.map(a=>`<tr><td><span class="badge ${a.strategy}">${labels[a.strategy]}</span></td><td>${yen(a.staked)}</td><td>${yen(a.returned)}</td><td class="${a.profit>=0?"positive":"negative"}">${yen(a.profit)}</td><td>${pct(a.roi)}</td><td>${pct(a.predictedRate*100)}</td><td>${pct(a.observedRate*100)}</td><td>${pct(a.calibrationGap*100)}</td><td>${a.brierScore.toFixed(3)}</td></tr>`).join("")}
function filteredCalls(){const purpose=$("#trace-purpose").value,strategy=$("#trace-strategy").value;return aiCalls.filter(c=>(purpose==="all"||c.purpose===purpose)&&(strategy==="all"||c.strategy===strategy))}
function renderCalls(){const rows=filteredCalls(),names={screening:"候補レースを選定",prediction:"最終判断",correction:"回答を再確認",audit:"監査"};$("#call-list").innerHTML=rows.map(c=>{const related=predictions.filter(p=>p.ai_call_id===c.id),race=related[0]?.races,bets=related.flatMap(p=>p.bets||[]),action=bets.length?"購入":related.length?"見送り":names[c.purpose]||c.purpose;return `<button class="call-item ${selectedCall===c.id?"active":""}" data-ai-call="${c.id}"><span><em class="decision-chip ${bets.length?"buy":related.length?"skip":"process"}">${action}</em><time>${clock(c.requested_at)}</time></span><strong>${race?`${esc(race.track)} ${race.race_number}R`:names[c.purpose]||c.purpose}</strong><small class="call-race-name">${race?esc(race.race_name):c.purpose==="screening"?"本日の全レースを比較":"Gemini AI処理"}</small><small>${c.status==="succeeded"?"✓ 正常完了":"処理状態: "+esc(c.status)}・${Number(c.input_tokens||0).toLocaleString()} tokens</small></button>`}).join("")||empty("条件に一致するAI処理はありません")}
function modelAnswer(response){const text=response?.candidates?.[0]?.content?.parts?.map(p=>p.text).filter(Boolean).join("\n");if(!text)return null;try{return JSON.parse(text)}catch{return text}}
function promptPayload(prompt){const value=String(prompt||"");for(let i=value.length-1;i>=0;i--){if(value[i]!=="["&&value[i]!=="{")continue;try{const parsed=JSON.parse(value.slice(i));if(Array.isArray(parsed))return parsed}catch{}}return []}
function inputView(call){const rows=promptPayload(call.request_json?.prompt);if(!rows.length)return `<div class="legacy-note">入力データを読み取れませんでした。</div>`;if(call.purpose==="screening")return `<div class="input-summary"><span><b>${rows.length}</b>件を分析</span><span><b>1</b>単一AI</span></div><div class="data-grid">${rows.map(r=>`<article class="data-card"><b>${esc(r.track||"分析結果")} ${r.race_number||r.raceNumber||""}R</b><strong>${esc(r.race_name||r.raceName||r.race_id||"")}</strong><small>${r.surface==="turf"?"芝":r.surface==="dirt"?"ダート":esc(r.surface||"")} ${r.distance?`・${r.distance}m`:""}</small></article>`).join("")}</div>`;return rows.map(r=>raceInputCard(r)).join("")}
function raceInputCard(row){const race=row.race||{},entries=row.entries||[],evals=row.evaluations||[],odds=row.odds||[],byNumber=new Map(entries.map(e=>[e.horseNumber,e]));return `<article class="input-race"><div class="input-race-head"><div><b>${esc(race.track)} ${race.raceNumber||race.race_number||""}R</b><strong>${esc(race.raceName||race.race_name||"")}</strong></div><span>${race.surface==="turf"?"芝":race.surface==="dirt"?"ダート":esc(race.surface||"—")} ${race.distance||"—"}m</span></div><h4>出走馬の総合評価</h4><div class="table-wrap compact"><table><thead><tr><th>馬</th><th>総合</th><th>能力</th><th>適性</th><th>状態</th><th>展開</th><th>推定勝率</th><th>品質</th><th>人気/単勝</th></tr></thead><tbody>${evals.sort((a,b)=>b.overallScore-a.overallScore).map(e=>{const entry=byNumber.get(e.horseNumber)||{};return `<tr><td><b>${e.horseNumber} ${esc(e.horseName||entry.horseName)}</b><small>${esc(entry.jockey||"")}</small></td><td><strong>${Number(e.overallScore).toFixed(1)}</strong></td><td>${Number(e.abilityScore).toFixed(1)}</td><td>${Number(e.suitabilityScore).toFixed(1)}</td><td>${Number(e.conditionScore).toFixed(1)}</td><td>${Number(e.raceContextScore).toFixed(1)}</td><td>${pct(Number(e.estimatedWinProbability)*100)}</td><td>${pct(Number(e.dataQuality)*100)}<small>${e.sampleSize}走</small></td><td>${entry.popularity||"—"}人気 / ${entry.winOdds||"—"}</td></tr>`}).join("")}</tbody></table></div><details><summary>AIが比較したオッズ ${odds.length}件</summary><div class="odds-grid">${odds.map(o=>`<span><b>${betLabels[o.type]||o.type} ${(o.horses||[]).join("-")}</b>${Number(o.odds).toFixed(1)}倍${o.popularity?`・${o.popularity}人気`:""}</span>`).join("")}</div></details></article>`}
async function openCall(id){selectedCall=id;renderCalls();const el=$("#trace-detail");el.innerHTML='<div class="loading">監査データを読み込んでいます…</div>';try{const [callRows,preds]=await Promise.all([api("ai_calls",`id=eq.${encodeURIComponent(id)}&select=*`),api("predictions",`ai_call_id=eq.${encodeURIComponent(id)}&select=id,strategy,action,confidence,reason,raw_response,races(track,race_number,race_name,start_time),bets(*),bet_decisions(*)&order=predicted_at`)]),call=callRows[0];if(!call)throw new Error("AI処理が見つかりません");renderTrace(call,preds)}catch(e){el.innerHTML=empty(e.message)}}
function renderTrace(call,preds){const answer=modelAnswer(call.response_json),decisions=preds.flatMap(p=>(p.bet_decisions||[]).map(d=>({...d,race:p.races,prediction:p}))),purchased=decisions.filter(d=>d.decision!=="rejected").length,rejected=decisions.filter(d=>d.decision==="rejected").length,bets=preds.flatMap(p=>p.bets||[]),primary=preds[0],verdict=bets.length?"購入":preds.length?"見送り":"候補を選定";$("#trace-detail").innerHTML=`<div class="trace-title"><div><span class="decision-chip ${bets.length?"buy":preds.length?"skip":"process"}">${verdict}</span><h2>${primary?`${esc(primary.races.track)} ${primary.races.race_number}R ${esc(primary.races.race_name)}`:call.purpose==="prediction"?"発走前の最終判断":"本日の候補レース選定"}</h2><p>${dt(call.requested_at)}・Geminiによる判断</p></div><div class="trace-summary"><b>${purchased}</b><small>有効</small><b>${rejected}</b><small>無効</small></div></div>
<section class="decision-overview"><div><p class="eyebrow">DECISION</p><h3>${bets.length?`${bets.length}点を購入`:preds.length?"このレースは見送り":"対象レースを絞り込み"}</h3><p>${primary?esc(primary.reason):"全レースを比較し、直前判断へ進める候補を選びました。"}</p></div>${primary?`<div class="confidence-ring" style="--confidence:${Number(primary.confidence||0)*3.6}deg"><strong>${Number(primary.confidence||0)}<small>%</small></strong><span>信頼度</span></div>`:""}${bets.length?`<div class="overview-tickets">${bets.map(b=>`<span><b>${betLabels[b.bet_type]||b.bet_type} ${(b.combination||[]).join("-")}</b>${yen(b.stake)}</span>`).join("")}</div>`:""}</section>
<div class="detail-divider"><span>詳しい判断過程</span></div>
<section class="trace-step"><div class="step-no">1</div><div><p class="eyebrow">AI INPUT</p><h3>AIに渡したデータ</h3><p>対象レース、出走馬の評価、予測確率、データ品質、オッズを読みやすく整理しています。</p><div class="hashes"><span>対象データ改ざん検知済み</span><span>${Number(call.input_tokens||0).toLocaleString()} tokens</span></div>${inputView(call)}</div></section>
<section class="trace-step"><div class="step-no">2</div><div><p class="eyebrow">AI RESPONSE</p><h3>AIの回答</h3>${renderAnswer(answer,preds)}</div></section>
<section class="trace-step"><div class="step-no">3</div><div><p class="eyebrow">TECHNICAL VALIDATION</p><h3>技術的な有効性確認</h3><p>プログラムは買い目の良し悪しを再判定せず、実在する馬・対応券種・100円単位・残高・オッズなどだけを確認します。</p>${decisions.length?decisions.map(decisionCard).join(""):`<div class="legacy-note">${call.purpose==="screening"?"この処理はレース候補の選定です。最終判断は発走約20分前にGeminiが行います。":"Geminiはこのレースを見送りました。"}</div>`}</div></section>
<section class="trace-step final"><div class="step-no">4</div><div><p class="eyebrow">FINAL RESULT</p><h3>最終結果</h3>${preds.length?preds.map(p=>`<div class="final-row"><b>${esc(p.races.track)} ${p.races.race_number}R ${esc(p.races.race_name)}</b><span>${p.action==="bet"&&(p.bets||[]).length?`${p.bets.length}点・${yen(p.bets.reduce((n,b)=>n+Number(b.stake),0))}`:"見送り"}</span></div>`).join(""):"後続の予測処理で購入を決定します。"}</div></section>`}
function renderAnswer(a,preds){if(!a)return `<div class="legacy-note">Geminiから有効な回答を取得できませんでした。</div>`;if(typeof a==="string")return `<div class="legacy-note">${esc(a)}</div>`;if(Array.isArray(a.selections))return `<div class="answer-box"><div><small>選定レース</small><strong>${a.selections.length}件</strong></div><div><small>全体判断</small><strong>${esc(a.overall_reason||"—")}</strong></div></div>${a.selections.map(x=>`<div class="selection-answer"><span class="badge single">優先 ${x.priority}</span><b>${esc(x.race_id)}</b><strong>T-20再取得</strong><p>${esc(x.reason)}</p>${(x.conflicts||[]).length?`<small>見解の相違：${esc(x.conflicts.join(" / "))}</small>`:""}</div>`).join("")}`;if(a.race_id||a.action){return `<article class="ai-prediction"><div><b>${a.action==="BET"?"ペーパーBET":"AI見送り"}</b><span>信頼度 ${a.confidence||0}%</span></div><p>${esc(a.reason)}</p>${a.rollover_plan?`<div class="rollover-plan"><b>ころがし方針</b><span>${esc(a.rollover_plan)}</span></div>`:""}${(a.data_caveats||[]).map(x=>`<small class="caveat">${esc(x)}</small>`).join("")}${(a.bets||[]).map(b=>`<div class="ai-bet"><b>${betLabels[b.bet_type]||b.bet_type} ${(b.horses||[]).join("-")}</b><span>提案 ${yen(b.stake)}</span><p>${esc(b.reason)}</p><small>金額根拠：${esc(b.stake_reason)}</small></div>`).join("")}</article>`}const list=a.predictions||[];return list.length?list.map(x=>renderAnswer(x,preds)).join(""):`<details><summary>GeminiのJSON回答</summary><pre>${esc(JSON.stringify(a,null,2))}</pre></details>`}
function decisionCard(d){const ok=d.decision!=="rejected";return `<article class="decision ${d.decision}"><div class="decision-state">${ok?"✓":"×"}<span>${ok?"有効":"無効"}</span></div><div><b>${betLabels[d.bet_type]||d.bet_type} ${(d.combination||[]).join("-")}</b><p>${esc(d.reason_detail||"技術的な形式を検証しました")}</p><div class="checks"><span>AI提案額 <b>${yen(d.proposed_stake)}</b></span><span>保存額 <b>${yen(d.final_stake)}</b></span><span>確認項目 <b>券種・馬番・100円単位・残高・オッズ</b></span></div></div></article>`}
function renderOperations(){const pipeline=pipelineItems.slice(0,40).map(x=>`<div class="audit-row"><b>${x.races?`${esc(x.races.track)} ${x.races.race_number}R`:dt(x.updated_at)}</b><span>${stateLabels[x.state]||esc(x.state)}<small>${x.races?esc(x.races.race_name):""}${x.selection_reason?` / ${esc(x.selection_reason)}`:""}${x.last_error?` / ${esc(x.last_error)}`:""}</small></span><em class="status ${x.state==="failed"?"failed":x.state==="completed"||x.state==="final_decided"?"succeeded":""}">${stateLabels[x.state]||x.state}</em></div>`).join("");const history=batches.map(b=>`<div class="audit-row"><b>${dt(b.started_at)}</b><span>${esc(b.parser_version)}<small>${b.races_fetched}レース / API ${b.api_requests}回${b.error_message?` / ${esc(b.error_message)}`:""}</small></span><em class="status ${b.status}">${b.status}</em></div>`).join("");$("#audit-list").innerHTML=pipeline||history||empty("履歴はありません")}
function empty(s){return `<div class="empty-state"><span>${esc(s)}</span></div>`}function showError(s){$("#error").hidden=false;$("#error").textContent=s}function logout(){localStorage.removeItem("race-lab-session");session=null;$("#auth").classList.remove("hidden")}
document.addEventListener("click",e=>{const page=e.target.closest("[data-page]"),strategy=e.target.closest("[data-strategy]"),card=e.target.closest("[data-open-strategy]"),call=e.target.closest("[data-ai-call],[data-open-call]");if(page){document.querySelectorAll("[data-page],.page").forEach(x=>x.classList.remove("active"));page.classList.add("active");$(`#${page.dataset.page}`).classList.add("active");$("#page-title").textContent=page.textContent.trim()}if(strategy){activeStrategy=strategy.dataset.strategy;renderToday()}if(card){activeStrategy=card.dataset.openStrategy;document.querySelector('[data-page="today"]').click()}if(call){document.querySelector('[data-page="trace"]').click();openCall(call.dataset.aiCall||call.dataset.openCall)}});
let installPrompt=null;window.addEventListener("beforeinstallprompt",event=>{event.preventDefault();installPrompt=event;$("#pwa-install").hidden=false});$("#pwa-install").addEventListener("click",async()=>{if(!installPrompt)return;await installPrompt.prompt();installPrompt=null;$("#pwa-install").hidden=true});window.addEventListener("appinstalled",()=>{$("#pwa-install").hidden=true;installPrompt=null});
if("serviceWorker" in navigator){window.addEventListener("load",async()=>{try{const registration=await navigator.serviceWorker.register("./sw.js");const showUpdate=worker=>{if(!worker)return;const toast=$("#pwa-update");toast.hidden=false;toast.querySelector("button").onclick=()=>worker.postMessage({type:"SKIP_WAITING"})};if(registration.waiting)showUpdate(registration.waiting);registration.addEventListener("updatefound",()=>{const worker=registration.installing;worker?.addEventListener("statechange",()=>{if(worker.state==="installed"&&navigator.serviceWorker.controller)showUpdate(worker)})});let refreshing=false;navigator.serviceWorker.addEventListener("controllerchange",()=>{if(refreshing)return;refreshing=true;location.reload()})}catch(error){console.warn("PWA registration failed",error)}})}
setInterval(()=>{if(session&&pipelineItems.length)renderDashboard()},30000);setInterval(()=>{if(session&&!document.hidden)load()},180000);
[$("#trace-purpose"),$("#trace-strategy")].forEach(x=>x.addEventListener("change",renderCalls));$("#logout").addEventListener("click",logout);$("#auth-form").addEventListener("submit",async e=>{e.preventDefault();try{$("#auth-message").textContent="ログイン中…";session=await auth("token?grant_type=password",{email:$("#email").value,password:$("#password").value});localStorage.setItem("race-lab-session",JSON.stringify(session));$("#auth").classList.add("hidden");$("#auth-message").textContent="";load()}catch(x){$("#auth-message").textContent=x.message}});$("#signup").addEventListener("click",async()=>{try{$("#auth-message").textContent="作成中…";const d=await auth("signup",{email:$("#email").value,password:$("#password").value,data:{display_name:$("#email").value.split("@")[0]}});$("#auth-message").textContent=d.access_token?"作成しました":"確認メールを送信しました"}catch(x){$("#auth-message").textContent=x.message}});$("#today-label").textContent=new Date().toLocaleDateString("ja-JP",{year:"numeric",month:"long",day:"numeric",weekday:"long"});if(session){$("#auth").classList.add("hidden");load()}
